### ISSUE TITLE
Remove letter

### ISSUE THREAD

**Issue by svennPT** [alexmacarthur/typeit#10]
Hello,

It's possible to remove letters with the same effect when writing?

Ex:
We love lorem ipsum (write all sentence)
We love (remove "lorem ipsum")
We love foo bar (write "foo bar")

Thanks and keep up the excellent work

**Comment by alexmacarthur** [comment]
Hi, svennPT -- thanks for the issue! Got a new version in the works that will allow this sort of thing and a lot more. Stay tuned!

**Comment by alexmacarthur** [comment]
@svennPT Just released a new version of TypeIt this afternoon. Introduces a set of companion functions that allows you to customize your typing like crazy. 

Release: https://github.com/alexmacarthur/typeit/releases/tag/v4.0.0

Demos: https://macarthur.me/typeit/
