### ISSUE TITLE
Conflict with Mathjax

### ISSUE THREAD

**Issue by rezaxdi** [alexmacarthur/typeit#100]
Hi there,

It seems this library is not compatible with mathjax, I just added typeit on a page where mathjax was already loaded and caused both not to work.

**Comment by alexmacarthur** [comment]
Could I see how you're implementing it and TypeIt? I've never heard of Mathjax before. If it's a custom display engine, I can't guarantee compatibility between it and TypeIt.

**Comment by rezaxdi** [comment]
Mathjax is for rendering math formulas and displaying Latex, MathML, etc. Here is a pen : https://codepen.io/rezaxdi/pen/rdzRWg you can remove typeit from header section and see mathjax works

**Comment by alexmacarthur** [comment]
Perfect - I'll check it out when I get a moment and see what's up!

**Comment by alexmacarthur** [comment]
@rezaxdi Sorry, just getting around to looking into this issue. It looks like the Mathjax library does quite a bit of custom DOM setup to do their thing -- so much that it's just not practical for me to configure TypeIt to work around it: 

![image](https://user-images.githubusercontent.com/8398220/38205175-3c58152a-366b-11e8-985a-86980117153c.png)

Unfortunately, it looks like you might need to to a different route for a typing animation if you're set on using that library.

**Comment by rezaxdi** [comment]
Hi again,
I was trying to make something and I actually did and I don't know why but the problem with the codepen I sent here is a weird thing ! inside setting section -> header I have added typeit just like how it is recommended in typeit tutorial like this : 
```
<script src="https://cdn.jsdelivr.net/npm/typeit@5.6.0/dist/typeit.min.js" />
```
now this prevents mathjax from working like it should ! I don't understand why. now if I change it to this : 
```
<script src="https://cdn.jsdelivr.net/npm/typeit@5.6.0/dist/typeit.min.js" ></script>
```
even the codepen works fine : https://codepen.io/rezaxdi/pen/xWzqYQ
