### ISSUE TITLE
Looping

### ISSUE THREAD

**Issue by tifnee** [alexmacarthur/typeit#107]
HI, I'm using the companion functions to type then delete 3 statements. I want to then loop the entire instance once its complete. The loop function does not seem to be working with the companion functions. Do yo have a solution for that? Thx!

**Comment by mrintegrity** [comment]
How did you solve this? I am also unable to get the looping to work with following code:

instance = new TypeIt('#type-it', {
  speed: 50,
  breakLines: false,
  loop: true,
  cursor: false
});

  instance.type("<span id='graphic'>graphic</span>").pause(500).delete(19);
  instance.type("<span id='product'>product</span>").pause(500).delete(19);
  instance.type("<span id='awesome'>awesome</span>").pause(500).delete(20);
  instance.type("<span id='uxui'>ux/ui</span>");

**Comment by alexmacarthur** [comment]
@mrintegrity Unless it's been resolved before then, I'll dig into this sometime this week.
