### ISSUE TITLE
Uncaught TypeError: $(...).typeIt(...).tiType is not a function

### ISSUE THREAD

**Issue by GeoffNeal** [alexmacarthur/typeit#11]
When using the advanced functions (i.e: tiType(), tiPause() etc), I had trouble getting them to work. I have since realised that I was using an outdated CDN (v3.0.1) that is displayed on the demo page of your plugin on unheap.com.

<a href="https://macarthur.me/typeit/">Here is the link</a>

Just so you know :)

**Comment by alexmacarthur** [comment]
Ahhh, thanks for letting me know! I'll get that updated ASAP.
