### ISSUE TITLE
nextStringDelay array option doesn't work on last string when looping

### ISSUE THREAD

**Issue by wkeithvan** [alexmacarthur/typeit#110]
When using {nextStringDelay: [500, 3000]}, there is a 3 second pause after every string finishes and half second delay between typing strings as expected. However, if {loop: true} is also specified, the last string has almost 0 pause between the typing finishing and the delete starting and then again almost 0 pause before the first string starts typing. Furthermore, if a loopDelay is specified, it seems to distribute across the last string and the pause, so adding {loopDelay: 10000} seems to add a 5 second pause before deleting the last string and a 5 second pause before typing the first string. This seems to be related to the fix made in #85.

`new TypeIt("#typeTitle", {
    strings: ["My first string", "The second string", "Here is the last string"],
    speed: 50,
    deleteSpeed: 40,
    breakLines: false,
    nextStringDelay: [500, 3000],
    loop: true
});`

**Comment by alexmacarthur** [comment]
Thanks for posting this! On it now.

**Comment by wkeithvan** [comment]
Thanks! Looks great now!
