### ISSUE TITLE
TypeIt adding superfluous whitespace characters?

### ISSUE THREAD

**Issue by dannymcgee** [alexmacarthur/typeit#113]
To be honest, I'm not 100% sure that this is a problem with TypeIt and not React, but I did some searching and couldn't find anything relevant for React.

I'm trying to get the effect of typing into an IDE (I'm building myself a new portfolio website), and I have several TypeIt instances activating one after another. I'm running some logic to add closing braces and indents automatically, insert new lines when the last one is complete, etc. For some reason, specifically on the lines with an indent (for some reason? I don't know if that's relevant), there's a single whitespace character being inserted at the beginning of the `data-typeitid` element and before the `.ti-container`.

Here's a screenshot of the problem: https://imgur.com/a/dYYyDEY

Can you think of any reason why this might be happening off the top of your head? I can upload the relevant source code if you want to take a look at it but I don't want to ask you to dig through all of my code looking for an error.

**Comment by mrintegrity** [comment]
I am also seeing this:

`      <h3>I am a<span class="type-it"></span></h3>

with:
```
  .type("<span id='graphic'>graphic</span>").pause(500).delete(19)
  .type("<span id='product'>product</span>").pause(500).delete(21)
  .type("n <span id='awesome'>awesome</span>").pause(500).delete(20)
  .type("<span id='uxui'>ux/ui</span>").pause(100000)
```

produces "I am a n awesome"

**Comment by mrintegrity** [comment]
Actually the "cursor" does seem to create a whitespace at the end of a string, even if showing the cursor is disabled.

**Comment by alexmacarthur** [comment]
Thanks for reporting this! What version of TypeIt are you using?

**Comment by mrintegrity** [comment]
5.10.2

**Comment by alexmacarthur** [comment]
Gotcha. Would you mind trying 5.10.6 and seeing if it's still an issue for you? Some recent changes may have addressed the issue you're dealing with.

**Comment by mrintegrity** [comment]
Sorry for the slow update, I am using a more recent version and the issue is no longer occurring

**Comment by luclemo** [comment]
I'm using version `5.10.7` and the whitespace problem is present.

My markup:

```html
<p>Inter<span class="blink"></span></p>
```
Options:
```javascript
new TypeIt('.blink', {
  strings: [
    "Change",
    "Act",
    "Cultural",
    "Sect",
    "Play",
    "Relate",
    "Mix",
    "Connect"
  ],
  breakLines: false,
  loop: true,
  cursor: false,
  speed: 200,
  nextStringDelay: [1000, 2000],
});
```

Expected: `InterChange` etc...

Output: `Inter Change` etc...

Demo: https://codepen.io/luclemo/pen/764da0346fa372fb34ce7bf86efd33f6

Any ideas how to fix this issue?

**Comment by arickconley** [comment]
This problem is present in the newest (v6.0.0) version.

**Comment by alexmacarthur** [comment]
I'll dig into this today!

**Comment by arickconley** [comment]
> I'll dig into this today!

The issue I'm having can be seen here:
https://codepen.io/arick/pen/jXovBR

I was able to to fix it by editing the minified version and removing the new line characters added in by babel when transpiling template tags. 

Also there is more whitespace to the end even when the cursor is disabled. 
https://github.com/alexmacarthur/typeit/blob/362f013b32a28b4da8a731a7693e65dae7d16c17/src/Instance.js#L377

Changing to `display: none` fixed it.
