### ISSUE TITLE
can the library be used for non-profit organisations without acquiring the license?

### ISSUE THREAD

**Issue by Parikshit-Hooda** [alexmacarthur/typeit#117]

**Comment by alexmacarthur** [comment]
Hi, @Parikshit-Hooda -- I don't know how I missed this! Sorry about that. 

A license is required for non-profit organizations, yes. Free licenses are limited to open source and personal projects at this time. 

Thanks,
Alex

**Comment by Parikshit-Hooda** [comment]
Okay. Thanks!
