### ISSUE TITLE
Infinite loop error

### ISSUE THREAD

**Issue by wiwimouse** [alexmacarthur/typeit#119]
If you pass text something like "><",  you'll get infinite loop in function "groupHTMLTags" and lead to browser crash.

**Comment by alexmacarthur** [comment]
Thanks for letting me know about this! I'll dig in and try to find a solution.

**Comment by alexmacarthur** [comment]
For personal reference, this appears to still be an issue. 

https://codepen.io/alexmacarthur/pen/LQzzPb?editors=1010

**Comment by alexmacarthur** [comment]
@wiwimouse Thanks for reporting this! This bug has been fixed in v6.0.2.
