### ISSUE TITLE
 I repeat the animation infinitely ?

### ISSUE THREAD

**Issue by Mineslu** [alexmacarthur/typeit#120]
Congratulations on the plugin. But I have a simple doubt. How do I repeat the animation infinitely ?. This is my code:

new TypeIt('.type-it', {
                speed: 50,
                loop:true,
                autoStart: false
            })
            .type('Wll')
            .pause(500)
            .delete(2)
            .type('ell, ');

Thank.

**Comment by alexmacarthur** [comment]
Sorry for the delay with this! Right now, the `loop` option can only be used for strings defined in the `strings` setting. Adding support for looping for complex sets of strings is already in the works, though.
