### ISSUE TITLE
Loop companion Functions

### ISSUE THREAD

**Issue by Samz3n** [alexmacarthur/typeit#126]
Hi, how do I loop typeit in a companion function?
"Loop: true" doesn't work .. I tried with reset() after last companion function but didn't work either and make all strings disappear.

**Comment by danielschweiger** [comment]
Any solution here, have the same problem? I want to restart everything after used some companion functions. @Samz3n @alexmacarthur

**Comment by Tobi2705** [comment]
Same here!

**Comment by alexmacarthur** [comment]
What @marcmoore said! v6 should address this. As a breaking change, however, you'll need to end your instance declaration with `.go()`.

Let me know if you still have troubles after that.
