### ISSUE TITLE
Cursor doesn't follow to next line when using firefox and safari browses

### ISSUE THREAD

**Issue by alfra432** [alexmacarthur/typeit#128]
you can also check it on your website: https://typeitjs.com/
i am using linux os, but I've also tried it on macos and windows10

**Comment by alexmacarthur** [comment]
Thank you for letting me know about this!

**Comment by vrk7bp** [comment]
For what it's worth, the break seems to come from the latest commit (be7f4d1). Reverting back to an earlier version of TypeIt.min.js worked fine on Firefox and Safari (MacOS).

**Comment by alexmacarthur** [comment]
Thanks, @alfra432 @vrk7bp! This issue's been fixed in v5.10.7. I appreciate your help in letting me know about this issue.
