### ISSUE TITLE
WebpackError: window is not defined

### ISSUE THREAD

**Issue by JoeSpencer** [alexmacarthur/typeit#129]
Using 'componentDidMount', deploy to Netlify is triggered by git merge 

Got this error during the Netlify build:

3:50:49 PM:   WebpackError: window is not defined
3:50:49 PM:   
3:50:49 PM:   - typeit.js:86 
3:50:49 PM:     ~/typeit/dist/typeit.js:86:1
3:50:49 PM:   
3:50:49 PM:   - typeit.js:11 window.TypeItDefaults.strings
3:50:49 PM:     ~/typeit/dist/typeit.js:11:1
3:50:49 PM:   
3:50:49 PM:   - typeit.js:14 Object.module.exports.pathContext
3:50:49 PM:     ~/typeit/dist/typeit.js:14:2
3:50:49 PM:   
3:50:49 PM:   - index.jsx:11 Object.exports.__esModule
3:50:49 PM:     src/pages/index.jsx:11:1
3:50:49 PM:   
3:50:49 PM:   - sync-requires.js:13 Object.exports.__esModule
3:50:49 PM:     .cache/sync-requires.js:13:52
3:50:49 PM:   
3:50:49 PM:   - static-entry.js:8 Object.<anonymous>
3:50:49 PM:     .cache/static-entry.js:8:1

**Comment by benday280412** [comment]
I'm also facing this issue, but when building using gatsby.

**Comment by alexmacarthur** [comment]
@JoeSpencer @benday280412 Thanks for letting me know! I have plans to address this in the next major version, but unsure when I'll get that knocked out.

**Comment by alexmacarthur** [comment]
This should no longer be an issue with v6 of the library.
