### ISSUE TITLE
Styling Companion Options?

### ISSUE THREAD

**Issue by joejlo** [alexmacarthur/typeit#13]
Is there anyway to CSS or HTML style a string when you use the .tiType() function? The project I'm working on is nearly all text and animation and I need to find a way to style individual words in a string.

I can style the whole sentence with the `<h1>` tag but a need it to be down to the word really.

So for example, in this snippet, I need the "(C) & (P)" and "version 1.0" a smaller font than the other words, so it would look like this as HTML: 

`<h1>PEUR - EXPLORER <span style="font-size: small;">(C) & (P)</span> \ <span style="font-size:small;">version 1.0</span><h1>`

Heres the current code: 

`<h1 id="title"></h1>`

`$('#title').typeIt({
     speed: 25,
     autoStart: false,
	 cursor: true
})
.tiType('PEUR - EXPLORER (C) & (P) \ version 1.0')`

**Comment by alexmacarthur** [comment]
Hi! Yup, you can just insert the inline styles and/or HTML with classes right into the function itself: 

```js
$('#title').typeIt({ 
speed: 25, 
autoStart: false, 
cursor: true }).tiType('PEUR - EXPLORER <span style="font-size: small;">(C) &amp; (P)</span> &#92; <span style="font-size:small;">version 1.0</span>')
```

Would that achieve what you're hoping? Here's a Codepen to demonstrate it too: 
http://codepen.io/alexmacarthur/pen/ZOevpG

**Comment by joejlo** [comment]
Thats perfect! I did try and do just that before I asked the question but it didn't work for some reason. Works great now, thanks a bunch!
