### ISSUE TITLE
Instance will not type after being emptied

### ISSUE THREAD

**Issue by RyanSchaefer** [alexmacarthur/typeit#131]
```
this.typeItInstance.empty();
this.typeItInstance.type('test');
```

will not produce typing within the element, but 
```
this.typeItInstance.type('test');
```
will.

**Comment by RyanSchaefer** [comment]
Furthermore, 

```
this.typeItInstance.empty().reset();
this.typeItInstance.type('test');
```
will work.

**Comment by RyanSchaefer** [comment]
The root cause seems like it is due to the queue not progressing after .empty() is called.

**Comment by alexmacarthur** [comment]
This issue is now resolved with v6 of TypeIt. When you call `.empty()` in a queue, you're able to queue further typing (and other actions) afterward.
