### ISSUE TITLE
I'm using version `5.10.7` and the whitespace problem is present.

### ISSUE THREAD

**Issue by luclemo** [alexmacarthur/typeit#132]
My markup:

```html
<p>Inter<span class="blink"></span></p>
```
Options:
```javascript
new TypeIt('.blink', {
  strings: [
    "Change",
    "Act",
    "Cultural",
    "Sect",
    "Play",
    "Relate",
    "Mix",
    "Connect"
  ],
  breakLines: false,
  loop: true,
  cursor: false,
  speed: 200,
  nextStringDelay: [1000, 2000],
});
```

Expected: `InterChange` etc...

Output: `Inter Change` etc...

Demo: https://codepen.io/luclemo/pen/764da0346fa372fb34ce7bf86efd33f6

Any ideas how to fix this issue?

_Originally posted by @luclemo in https://github.com/alexmacarthur/typeit/issue_comments#issuecomment-432848370_

**Comment by luclemo** [comment]
Setting `.blink` to `display: inline-block;` seems to resolve it.

**Comment by alexmacarthur** [comment]
Glad you found a solution, @luclemo -- sorry for the initial hassle.
