### ISSUE TITLE
Keypress?

### ISSUE THREAD

**Issue by AI-Guru** [alexmacarthur/typeit#133]
Namaste!

Great library! What do you think? Would it be possible to somehow pause an animation until the user presses a key on the keyboard?

Best,
Tristan

**Comment by alexmacarthur** [comment]
Thanks! Yes, definitely. I don't have the bandwidth to go into detail on it here, but after you create an instance of TypeIt, you could `freeze()` and `unfreeze()` as needed, depending on when the user takes action. If you're not doing any typing until the user takes action, then you could just hold off on calling the `.go()` method to kick it off. 

```js
const instance = new TypeIt('#element', {
     strings: "My string!"
});

window.addEventListener('event', function (e) {
     if(conditionsAreMet) {
          instance.go();
     }
});
```
