### ISSUE TITLE
Trigger start with a click or link?

### ISSUE THREAD

**Issue by joejlo** [alexmacarthur/typeit#14]
Is it possible to trigger the animation to start by clicking a link? I have a second page that I want to reveal by clicking a menu option, but when I click it the animation has already taken place. So I'm wondering if I can trigger it to start when the link is clicked?

Heres a basic version - [JSFiddle](https://jsfiddle.net/psgm8equ/1/)

**Comment by alexmacarthur** [comment]
Yup, that's no problem. You just need to call typeIt() on your element AFTER you've clicked your element, instead of just having it type automatically on page load. I'd use a setup similar to this: 

https://jsfiddle.net/amacarthur89/psgm8equ/10/

The important part is this general setup: 

```js
$('element').on('click', function() {
     $('other_element').typeIt();
});
```

**Comment by joejlo** [comment]
That works really well, but how would I achieve the same effect for multiple pages? There's going to be about 5 or 6 pages in total and to get the effect I want they'll have to be all swappable, with a nav on each page

I tried this, and each page reveals the correct content but not the links, what am I doing wrong? - [JSFiddle](https://jsfiddle.net/psgm8equ/11/)

**Comment by alexmacarthur** [comment]
Try this out -- I've made functions that more easily handle multiple pages. All you need to do is make sure you add data-* attributes to the new pages you add. See markup for how I have that laid out: 

https://jsfiddle.net/amacarthur89/wga61bau/17/

**Comment by alexmacarthur** [comment]
Closing since conversation's been moved outside Github and doesn't appear to be any issue with TypeIt itself.
