### ISSUE TITLE
Allow reset() to accept updated options.

### ISSUE THREAD

**Issue by alexmacarthur** [alexmacarthur/typeit#141]
When an instance is `reset()`, allow user to pass new options without reselecting element. If no options are passed, use the original.

```js
const instance = new TypeIt('#element', {
   strings: 'old string',
   speed: 50
});

instance.reset({
   strings: 'new string', 
   speed: 25
});
```

**Comment by Stevens1995** [comment]
if the new strings of the opts are not provided, should the previous queue be cleared or not?

**Comment by Stevens1995** [comment]
should the new options overwrite the previous options or just combine with the default options?
