### ISSUE TITLE
Can't use html code with span in h2

### ISSUE THREAD

**Issue by maxleistner** [alexmacarthur/typeit#145]
I am trying to let typeit type the following html code. Why does it not work? 
```
<h2>Hello i am a text<span> and i am in a span</span></h2>
```

**Comment by alexmacarthur** [comment]
Thanks for reporting! This is a known limitation that I used to have better documented. I'll keep this issue open to track progress on adding nested HTML as a feature.

**Comment by akbr** [comment]
Here's a sandbox showing conversion of nested HTML into a TypeIt-like queue form (without any regex!):

https://codesandbox.io/s/4wlp91ol94?expanddevtools=1&fontsize=14

@alexmacarthur : My syntax is a little different than yours, but it should be pretty easy to take a similar approach with `noderize`.

**Comment by alexmacarthur** [comment]
@akbr This is amazing. Thanks for sharing that. When I get a moment, I'll dig in and see how this might incorporate with how TypeIt's currently set up.

**Comment by alexmacarthur** [comment]
Support added in latest release!

https://github.com/alexmacarthur/typeit/releases/tag/v6.1.0

**Comment by paskainos** [comment]
This works great! One thing I noticed though; now (v. 6.1.1) lone `<span>` elements seem to get subsumed into the cursor `<span>`.

- v. 6.0.3 renders lone `<span>`: https://codepen.io/paskainos/pen/xxbVYRY
- v. 6.1.1 subsumes lone `<span>`: https://codepen.io/paskainos/pen/xxbVYOY
