### ISSUE TITLE
KeyUp KeyDown simulation 

### ISSUE THREAD

**Issue by beshoo** [alexmacarthur/typeit#146]
Dear all, I am trying to imitate a keyboard action to post a comment to my Instagram photo.
Well, I inject the plugin to the Instagram page in my browser and can type but the submit button is not enabled, but if I click any keyboard button is activated.

So it is obvious  "typeit" is not sending keystroke code!
Please advice

**Comment by alexmacarthur** [comment]
Hi, @beshoo. I'm not sure what issue you're exactly having. Do you have any screenshots and further details you could post?

**Comment by alexmacarthur** [comment]
Closing since I don't quite understand the issue yet. Feel free to reopen if it's still a problem!

**Comment by beshoo** [comment]
Well let me be more clear,
I want to auto reply to my friend post who post on my pictures. 

So i need to auto type in the instagram website, what i did, i install inject javascript to my chrome, and injected typeit and ask typeit to type in the comment textaria.

It type, no problem with that. 
But when you type by your real keyboard in the instagram comment box. The post button activated due to key down event. 

Well, typeit, it seem not fire that event or it is but chrome did not read it. The post button still off when i type via typeit. 
@alexmacarthur
