### ISSUE TITLE
"Fast forwarding" to end of queue?

### ISSUE THREAD

**Issue by akbr** [alexmacarthur/typeit#147]
Is there any way to "fast forward" the end of an active queue? For example:

```javascript
let instance = new TypeIt('#type', {speed: 100});
instance
  .type('blah blah blah blah blah')
  .break()
  .type('blah blah blah blah blah')
  .break()
  .type('The answer is 42.');
```

Imagine the user gets tired of waiting and just wants to get to the answer. Is there a way to speed to the end of the queue once it's started?

**Comment by alexmacarthur** [comment]
You _could_ try using the `.options()` method to dramatically increase the speed of the animation. Haven't tested this, but something like this: 

```diff
let instance = new TypeIt('#type', {speed: 100});
instance
  .type('blah blah blah blah blah')
+ .options({speed: 5})
  .break()
  .type('blah blah blah blah blah')
  .break()
  .type('The answer is 42.');
```

That said, there's nothing currently built into "snap" it to completion, although I do like that idea.

**Comment by akbr** [comment]
Thanks for the response, @alexmacarthur! That does work for subsequent items in the queue, once the first `type` command has completed.

What I _really_ want is to arbitrarily jump to the end result of a long, already-formed queue (e.g., in response to user input).

It looks like this functionality would require some significant changes to the library, particularly in how Promises are chained/queued, so I'm going to close this issue for now.

P.S. - I was able to achieve the effect I wanted using your `noderize` helper along with a different queue style (driven by a ticker instead of Promises). Happy to share some ideas once I've had a chance to play around more.
