### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by badkyi** [alexmacarthur/typeit#148]
Using v6.0.2 with NextJS & componentDidMount, I'm getting this error. I'm guessing it's because of the SSR. Any plans to make this library compatible with this?

(currently using version 5.0.2 as a workaround).

**Comment by alexmacarthur** [comment]
Thanks for reporting! This is interesting because `componentDidMount` is where Next recommends you put code that depends on the `window` object: 

https://github.com/zeit/next.js/wiki/FAQ

You wouldn't happen to have a brief snippet of code to show how you have things wrapped up, would you?

**Comment by badkyi** [comment]
`import React, { Component } from "react";
import TypeIt from "typeit";

class Type extends React.Component {
  constructor(props) {
    super(props);
    this.state = {};
    this.el = React.createRef();
  }

  componentDidMount() {
    new TypeIt(this.el.current, this.props);
  }

  render() {
    return <span ref={this.el}>{this.props.children}</span>;
  }
}

export default class Index extends Component {
  constructor(props) {
    super(props);
    this.state = {};
  }

  render() {
    return (
      <>
        <Type
          strings={[
            "some <strong>text</strong>.",
            "more <strong>text</strong>.",
            "even more <strong>text</strong>."
          ]}
          loop={true}
          speed={60}
          cursor={false}
          breakLines={false}
          nextStringDelay={1000}
        />
      </>
    );
  }
}
`

**Comment by badkyi** [comment]
`import React, { Component } from "react";
import TypeIt from "typeit";

class Type extends React.Component {
  constructor(props) {
    super(props);
    this.state = {};
    this.el = React.createRef();
  }

  componentDidMount() {
    new TypeIt(this.el.current, this.props);
  }

  render() {
    return <span ref={this.el}>{this.props.children}</span>;
  }
}

export default class Index extends Component {
  constructor(props) {
    super(props);
    this.state = {};
  }

  render() {
    return (
      <>
        <Type
          strings={[
            "some <strong>text</strong>.",
            "more <strong>text</strong>.",
            "even more <strong>text</strong>."
          ]}
          loop={true}
          speed={60}
          cursor={false}
          breakLines={false}
          nextStringDelay={1000}
        />
      </>
    );
  }
}`

**Comment by alexmacarthur** [comment]
Got an update on this! Would you mind trying to install off of the `window` branch and running Next again? I'm seeing success on my end. You can run this command: 

`npm install github:alexmacarthur/typeit#window`

**Comment by badkyi** [comment]
@alexmacarthur Hey Alex, I'm now getting this error: 'TypeError: Cannot read property 'tagName' of null'.

**Comment by alexmacarthur** [comment]
Hi, @badkyi -- It looks like this is happening because `this.el.current` is returning `null`. If I set that ref you created to an element in the `render()` method, everything appears to work correctly: 

```js
import React, { Component } from "react";
import TypeIt from "typeit";

export default class TypeItComponent extends React.Component {
    constructor(props) {
        super(props);
        this.state = {};
        this.el = React.createRef();
    }

    componentDidMount() {
        new TypeIt(this.el.current, this.props).go();
    }

    render() {
        return (
            <>
                <span ref={this.el}></span>
                {this.props.children}
            </>
        );
    }
}
```

**Comment by badkyi** [comment]
Everything appears to be working fine now, thanks Alex!
