### ISSUE TITLE
fadeTo is not a function

### ISSUE THREAD

**Issue by denniskkim** [alexmacarthur/typeit#15]
Hey, i keep getting this error, but cant figure out what its complaining about:
typeit.js:368 Uncaught TypeError: t.el.find(...).fadeTo is not a function

im storing my string in my html file and following the steps.

all i have in my .js file is:
$('.line1').typeIt({
});

thanks in advance!

**Comment by ramezrafla** [comment]
https://api.jquery.com/fadeTo/
Are you sure you properly included jQuery and waited for it to load?

**Comment by alexmacarthur** [comment]
Hi, @denniskkim -- Were you able to confirm this wasn't because jQuery wasn't properly loaded?
