### ISSUE TITLE
Calling .destroy() on afterComplete's instance parameter isn't removing the cursor.

### ISSUE THREAD

**Issue by jerryq27** [alexmacarthur/typeit#153]
First off, great plugin!

I was trying to chain two TypeIt instances with two different elements; the site's title and description.
Since they both have different styles, I don't think I could've used the same instance.

I went ahead with using two instances, but having two cursors didn't look that great, so in order to remove the cursor after the title's animation was finished, I had to do the following:

```javascript       
let typeIt = new TypeIt("#site-title", {
    strings: ["Title"],
    cursorChar: "_",
    afterComplete: instance => {
        new TypeIt("#site-description", {
            strings: ["Description"],
            cursorChar: "_",
        }).go();

        // instance.destroy(); <- this didn't work in removing the cursor.
        typeIt.destroy(); // Had to use this workaround, using the named instance.
    },
}).go();
```

Shouldn't `instance.destroy()` have been able to remove the cursor after the title's animation?

**Comment by xavierfoucrier** [comment]
I can confirme the behavior... may be it would be cool to have an option, like `cursorBefore: true|false` to do that automatically at the end of the type process. :wink:

**Comment by tiadaguru** [comment]
Agreed! 

Is there a workaround to remove the _second_ instance's cursor after animation? I might be missing something obvious, but destroying the 2nd instance removes its cursor from the full animation (as if you'd set `cursor = false,` )

https://codepen.io/TG2-/pen/abbdRxL

```
var typeIt = new TypeIt("#site-title", {
    strings: ["Title"],
    cursorChar: "_",
    afterComplete: instance => {
        var typeIt2 = new TypeIt("#site-description", {
            strings: ["Description"],
            cursorChar: "_",
        }).go();
        typeIt.destroy();
        typeIt2.destroy();
    },
}).go();
```
