### ISSUE TITLE
No delete

### ISSUE THREAD

**Issue by mmorainville** [alexmacarthur/typeit#154]
Hi,

Is there an option to disable the delete animation?
I've tried setting the `deleteSpeed` property to 0 but it doesn't work, the animation is still there.

**Comment by alexmacarthur** [comment]
Do you have an example for when you'd want to disable deletion?

**Comment by mmorainville** [comment]
Hi @alexmacarthur 

For example if I want to do a "Gameboy Advance Pokemon-style dialog" where the text appears with the typing animation but if the player hits Enter to skip the dialog it should display the rest of the sentence immediately (thus with no animation/delay).

**Comment by alexmacarthur** [comment]
@mmorainville Super late getting back to you on this (it may not even be useful to you anymore 🤣 ), but this'll be coming in v8, so stay tuned for a bit longer!

**Comment by mmorainville** [comment]
Ahah no problem @alexmacarthur better late than never 😉
And I'm sure it will be useful to other people!
Keep up the good work!

**Comment by alexmacarthur** [comment]
v8 allows you to pass an `instant` parameter to the `.delete()` method. More on that here: 

https://typeitjs.com/docs/vanilla/instance-methods#delete
