### ISSUE TITLE
Inline styles cause problems for Content Security Policy

### ISSUE THREAD

**Issue by RBrNx** [alexmacarthur/typeit#158]
### Issue

The following styles that are created in `instance.js` by TypeIt violate a strict Content Security Policy that does not include `style: unsafe-inline`. 

`let baseInlineStyles = "display:inline;position:relative;font:inherit;color:inherit;line-height:inherit;";`

Here you can see the error produce by Chrome:
![image](https://user-images.githubusercontent.com/1332314/62788550-09f3c000-babf-11e9-903d-6ed8c996f93e.png)

### Solution

Perhaps these inline styles can be moved into a class, and appended to the DOM via the already existing `appendStyleBlock` function used in TypeIt.

**Comment by alexmacarthur** [comment]
Dang - thanks for reporting! I'll see what I can do.

**Comment by alexmacarthur** [comment]
This is a far trickier issue to tackle than I had first imagined. Not taking any action, since it's probably best anyway that individual site managers address it via their own CSPs.
