### ISSUE TITLE
afterString: instance.freeze is not a function

### ISSUE THREAD

**Issue by fakenine** [alexmacarthur/typeit#159]
Hello!

I would like to call `instance.freeze()` after each string, wait for the user to press spacebar, then unfreeze the instance...but I'm getting the following message:

`TypeError: instance.freeze is not a function`

ie:

```javascript
  $(document).ready(function() {
    new TypeIt('#text', {
      strings: ['Hello', 'How are you?'],
      speed: 50,
      afterString: (step, queue, instance) => {
        instance.freeze();
        $(window).keypress(function(e) {
          if (e.which === 32) {
            instance.unfreeze();
          }
        });
      },
    }).go();
  });
```

**Comment by alexmacarthur** [comment]
The reason for this is that the `freeze` and `unfreeze` methods are only available on the parent `TypeIt` instance -- not the individual sub-instances of that parent. To achieve the effect you're looking for you, this should work: 

```diff
    $(document).ready(function () {
      new TypeIt('#text', {
        strings: ['Hello', 'How are you?'],
        speed: 50,
        afterString: (step, queue, instance) => {
-         instance.freeze();
+         instance.status.frozen = true;

          $(window).keypress(function (e) {
            if (e.which === 32) {
-             instance.unfreeze();
+             instance.status.frozen = false;
+             instance.fire();
            }
          });
        },
      }).go();
    });
```

It's a bit more verbose, but gets you the same result. I'll keep this issue in mind for future updates -- I can see the confusion.

**Comment by alexmacarthur** [comment]
This has been addressed in the latest release! Now, `instance` will correctly refer to the parent `TypeIt` instance.

**Comment by fakenine** [comment]
@alexmacarthur Cool ! Thank you :)
