### ISSUE TITLE
breakDelay not working as expected

### ISSUE THREAD

**Issue by shahzeb1** [alexmacarthur/typeit#16]
I'm using the `breakDelay` property set to 4000 (or 4 seconds), yet the deleting just continues on without any delay. Quite confused as to why this is.

``` javascript
    $('.translation').typeIt({
        strings: ['hi', 'hello', 'bonjour'],
        cursor: false,
        loop: true,
        deleteSpeed: 200,
        speed: 200,
        lifeLike: true,
        breakDelay: 4000,
        breakLines: false
    });
```

<details>
 <summary>

Other details</summary>

jQuery version: 3.1.0
Browser: Chrome 52.0.2743.116
Platform: Macbook
</details>

**Comment by shahzeb1** [comment]
**Discovery:** As long as all other options are removed, then it seems to work as expected. But as soon as new parameters are added, it doesn't respect the breakDelay property:

To test it out, comment out any of these lines and you'll see the difference:
```javascript
$('.translation').typeIt({
		strings: ['hi', 'hello', 'bonjour'],
		breakDelay: 4000,
		cursor: false,
		// loop: true,
		// deleteSpeed: 200,
		// speed: 200,
		// lifeLike: true,
		// breakLines: false
	});
```

**Comment by alexmacarthur** [comment]
Hi, @shahzeb1 -- 

Thanks for asking about this! The `breakDelay` option is only valid if `breakLines` is set to true. If you'd like to set a pause between typing each string, right now, the only option is the use the companion functions provided in the plugin -- `tiPause()`, which requires a little bit different setup, something like this:

```js
$('.translation').typeIt()
.tiType('hi')
.tiPause(4000)
.tiDelete()
.tiType('hello')
.tiPause(4000)
.tiDelete()
.tiType('bonjour');
```

Sorry about the confusion -- the documentation isn't clear and it isn't the cleanest option. Will definitely note this for a future version. 

Alex

**Comment by shahzeb1** [comment]
Thank you.

**Comment by alexmacarthur** [comment]
Hi, @shahzeb1 -- Letting you know there's a new release out that resolves this issue by introducing a 'deleteDelay' option. Your feedback on this has been greatly appreciated.

Thanks for using TypeIt! If you don't mind staring and/or sharing the project, I'd really appreciate it!
