### ISSUE TITLE
Word by word rather than letter by letter - is this possible?

### ISSUE THREAD

**Issue by peter-mead** [alexmacarthur/typeit#163]
Apologies - First time using Github, not sure if this is appropriate?

I checked all docs, and examples - is it possible to type a string one word at a time, instead of one letter at a time, or better than that, to alternate for any give string.

It's a great plugin, has saved me muchos time, much appreciated.

**Comment by alexmacarthur** [comment]
Absolutely appropriate! That's not a feature right now, but definitely open to the idea. I'll flag this as a possibility for a future release.

**Comment by peter-mead** [comment]
Thanks for that :)

**Comment by khushit-shah** [comment]
peter-mead you can try [Cursor.js](https://github.com/khushit-shah/Cursor.js) it offers word by word functionality too!

**Comment by alexmacarthur** [comment]
Although it doesn't give the same ergonomics as a dedicated option, the relatively new `instant` option that can be passed into each instance method can help with this. I have no interest in building this feature out now, but come back if it's still something you're passionate about. 

https://www.typeitjs.com/docs/vanilla/instance-methods#instantly-executing-an-action
