### ISSUE TITLE
Using TypeIt in a placeholder

### ISSUE THREAD

**Issue by Caroliveira** [alexmacarthur/typeit#172]
I couldn't use it, there's anyone who know how?

My code: (obs: I'm using Reactstrap)
<Input
    id="subscribe-input"
    defaultValue=""
    placeholder="Enter your email..."
    type="text"
/>

**Comment by alexmacarthur** [comment]
Sorry, using TypeIt with placeholders currently isn't possible and probably won't be built in anytime soon.
