### ISSUE TITLE
Ability to add an element around each character as it's typed

### ISSUE THREAD

**Issue by joshuatuscan** [alexmacarthur/typeit#173]
I'd love to be able to play with animation effects on each character as it appears, for example a simple fade in as each character is typed. I haven't seen a way to add this in as an option, is there some other way this could be accomplished with the current codebase?

**Comment by alexmacarthur** [comment]
Great idea. I'm not sure of the best implementation, but I love the idea of allowing people to control and fine-tune the animation of each character as it's typed on the screen. I've moved this to a discussion. Post there with more thoughts if you have them. 

https://github.com/alexmacarthur/typeit/discussions/309
