### ISSUE TITLE
Span and Cursor...

### ISSUE THREAD

**Issue by dtcblyth** [alexmacarthur/typeit#175]
Hi Alex,

I recently updated from v6.0.3 to v6.1.1 of typeit. Previously I was able to include span elements in typed text. I would do this to style individual words within the typed text. In the latest version, however, text within my span elements seems to get added to the .ti-cursor span element and all styling is lost.

For example, where previously something like this…
`This is a <span style="color:red;">RED</span> word`

… would type correctly as…
`This is a RED word |`

…now it types like…
`This is a word | RED `

… with both the cursor character and the word RED flashing as part of the .ti-cursor element.

Thanks for help!
D.

**Comment by alexmacarthur** [comment]
Definitely a bug. Thanks for reporting! I'll try to get to this as soon as I can.

**Comment by KrYpTeD974** [comment]
Duplicate with : 
https://github.com/alexmacarthur/typeit/issues/174

**Comment by dtcblyth** [comment]
> Definitely a bug. Thanks for reporting! I'll try to get to this as soon as I can.

No worries. Thanks Alex! Will I get some sort of notification when the update is available or should I just keep an eye on the github project?

**Comment by alexmacarthur** [comment]
Fixed in v6.1.2!

**Comment by dtcblyth** [comment]
Thanks Alex!
Will check it out.
