### ISSUE TITLE
[feature request] Option to type "after" preexisting  element text

### ISSUE THREAD

**Issue by aritsune** [alexmacarthur/typeit#176]
As far as I can tell, right now you can only either (A) delete all preexisting text in the target element before typing, or (B) type all preexisting text in the element before typing the queued strings.

It would be nice to have an option where TypeIt simply leaves the preexisting text alone and types its strings after it - especially in my situation as I want to be able to type more text on user input.

**Comment by alexmacarthur** [comment]
Great call-out... I'm moving this to a discussion for future ideation/thoughts. Feel free to weigh in more there if you have anything to add. 

https://github.com/alexmacarthur/typeit/discussions/308
