### ISSUE TITLE
Buggy behavior on Google Chrome using gradients & Cursor gradient bug

### ISSUE THREAD

**Issue by Zyrophr** [alexmacarthur/typeit#177]
Heya! 
So I've been trying to understand why my website's title was broken on Google Chrome (it works fine on Firefox and Safari), and I noticed that because I had set the text color to fully transparent so I could use a gradient, it messes up completely with typeit on Chrome. 
*I also noticed that using a gradient breaks the blinking cursor. It becomes invisible. Regardless of the browser.*

If I remove the transparency and use a single color, it works fine on every browser. 

### Here is what I'm doing:

_This is my html code, where I set my headers_
```html
<h1 class="text-center mg-clear hero-header-text btn-resize-mode text-gradient">
    > <span class="terminal-effect"></span><br>
</h1>
<h2 class="mg-md text-lg-center h2-style text-gradient">
    <span class="type-effect"></span><span class="cursor-effect"></span>
</h2>
```

_Those are the typeit scripts tags_
```javascript
<script>
	new TypeIt('.type-effect', {
		cursor: false,
		lifeLike: true,
		startDelay: 900,
		deleteSpeed: 75
	})
	.type("Programmer")
	.pause(900)
	.delete(10)
	.pause(750)
	.type("Coder?")
	.pause(550)
	.delete(6)
	.pause(650)
	.type("Developer.")
	.go();
</script>
<script>
	new TypeIt('.cursor-effect', {
		cursor: false,
		lifeLike: false,
		startDelay: 900,
		loop: true
	})
	.type("|")
	.pause(650)
	.delete(1)
	.go();
</script>
<script>
	new TypeIt('.terminal-effect', {
		cursor: false,
		startDelay: 900,
		lifeLike: true,
	})
        .type("name")
	.go();
</script>
```

And lastly, this is the css:
```CSS
.text-gradient {
	background-clip: text !important;
	-webkit-background-clip: text !important;
	background: linear-gradient(29deg, #8685EF, #00E7B2);
	color: transparent !important;
}
```

It would be awesome if this could be fixed, or if it's on my end, if I could have some help!

Thanks :)

**Comment by alexmacarthur** [comment]
Hi! Super late to getting this.. sorry about that. I'm not able to replicate the issue myself, but I do notice you're using a non-conventional cursor approach. Is there a reason for this? Regardless, I'm highly confident this is something more to do with your particular implementation, rather than the library itself. Closing for now, but let me know if this is still an issue with perhaps a link to a live demo of it occurring.
