### ISSUE TITLE
Incorrect handling of surrogate pairs

### ISSUE THREAD

**Issue by PicturElements** [alexmacarthur/typeit#179]
Looks like emoji and other surrogate pairs are being incorrectly split (tested via demo):

```javascript
// TypeIt.js split
split("testing🤔") -> ["t", "e", "s", "t", "i", "n", "g", "�", "�"];
```

Which results in text being typed as follows:

testi
testin
testing 
testing�
testing🤔

Perhaps an alternate surrogate pair aware split would help:

```javascript
// spread split (or Array.from)
[..."testing🤔"] -> ["t", "e", "s", "t", "i", "n", "g", "🤔"];
```

**Comment by alexmacarthur** [comment]
Thanks for reporting this!
