### ISSUE TITLE
Wrong NPM release version

### ISSUE THREAD

**Issue by xavierfoucrier** [alexmacarthur/typeit#187]
Hi @alexmacarthur,

Just to let you know, the `6.1.5` release on Github is marked as `typeit@6.5.0` on NPM.
Feel free to close this issue when it is fixed. :wink:

**Comment by alexmacarthur** [comment]
oh no! thanks for telling me about this! 🤦‍♂

**Comment by xavierfoucrier** [comment]
Your releases are coming out too quickly haha :smile: :rocket: :fire:
