### ISSUE TITLE
Clarification on software license

### ISSUE THREAD

**Issue by frewsxcv** [alexmacarthur/typeit#19]
The [package.json](https://github.com/alexmacarthur/typeit/blob/master/package.json#L7) file mentions "General Public License", though it's not obvious to me which license this is. Is this a reference to the GNU General Public License? If so, what version? The [NPM docs](https://docs.npmjs.com/files/package.json#license) recommend using the SPDX license identifier to make this more clear for the user.

**Comment by alexmacarthur** [comment]
Thanks, @frewsxcv. This will be clarified in the next release.

**Comment by alexmacarthur** [comment]
Hi, @frewsxcv -- Letting you know there's a new release out that clears up this confusion. 

Thanks for checking out TypeIt! If you don't mind staring and/or sharing the project, I'd really appreciate it!
