### ISSUE TITLE
Empty String in Array Causes Failure

### ISSUE THREAD

**Issue by jwk4946** [alexmacarthur/typeit#199]
if there is an empty string in array it causes the entire thing not to render

`const myArr = ['', 'foo', 'bar'];`
`new TypeIt("#myElement", {
  strings: myArr
}).go();`

this does not work - it fails to render at all - but if you put a space in the 0th element it works as expected

**Comment by alexmacarthur** [comment]
thanks for reporting this! i'll check it out and aim for an update being ready tomorrow at some point.

**Comment by alexmacarthur** [comment]
Got to this earlier than expected.[ v7.0.1](https://github.com/alexmacarthur/typeit/releases/tag/v7.0.1) fixes this issue. Thanks again for reporting.

**Comment by jwk4946** [comment]
Thanks for responding and quick fix. Stay safe!
