### ISSUE TITLE
typeit animation on input field in react

### ISSUE THREAD

**Issue by ginccc** [alexmacarthur/typeit#201]
Hi,

i am trying to get typeit animation work in an input field in react, but always get this error here:

![image](https://user-images.githubusercontent.com/20626330/77889567-5b2f0a80-726e-11ea-93d1-2540c6b36e82.png)

InputField Component:
````
 render() {
        return (
            <div className="inputFieldContainer">
                <input id="userInputField" autoFocus ref={this.inputRef} className="inputField"/>
                <button type="submit" onClick={this.say}>reply</button>
            </div>
        );
    }
````

Any ideas on how to get this to work? I have seen the animating text in inputfield works in your docs, but does this work in react as well?!

Thanks
Gregor

**Comment by alexmacarthur** [comment]
Hi! I noticed you're referencing `#userInputField` when creating a new instance of TypeIt. This should instead be using `this.inputRef.current`, so you can safely target the element you'd like the animation to appear on: 

```javascript
new TypeIt(this.inputRef.current, {
   strings: inputFieldValue, 
   waitUntilVisible: true
});
```

Try that and let me know if you have any success! Also, if you ever wanted to shift from this approach, there's a TypeIt React component out there as well, which might help abstract away some of the setup:

https://github.com/alexmacarthur/typeit-react

**Comment by ginccc** [comment]
thanks for your prompt answer!

i have tried this, but it still gives me this error: 

![image](https://user-images.githubusercontent.com/20626330/77918376-17eb9080-729c-11ea-8f12-962bfef24c2b.png)


Also, i am using the react plugin, it works great, but how can i use it on input fields which don't allow any child components?

**Comment by alexmacarthur** [comment]
Ah! I see a little better now. Since you're using `typeit-react`, you don't need to manually create any instance with `new TypeIt()`. Instead, you can drop in the `<TypeIt />` component and set the `element` to `input`. Something like this (really rough, but hopefully it sets you on a good path):

```js
  setStringToType(instance) {
    instance.type(this.props.inputFieldValue)
    return instance;
  }

  render() {
    return (
      <div className="quickReplyContainer">
        <TypeIt 
          getBeforeInit={this.setStringToType}
          element={"input"}
        />
      </div>
    )
  }
```

With this, you'll just need to pass set what to type inside the `getBeforeInit` prop on the component. Let me know if this makes sense or helps a bit.

**Comment by ginccc** [comment]
Thank you for the input. It is indeed helping me forward, but i am struggling now with the params for the input field.

Here is my current input field: 
```
<input id="userInputField" autoFocus onKeyDown={this.keyPress} autoComplete="off" ref={this.inputRef} className="inputField"/>
```

How do i configure TypeIt to pass the fields to the input element?

I tried it like this, but no success. 
```
<TypeIt
             getBeforeInit={this.setStringToType}
             element={"input"}
             autoFocus onKeyDown={this.keyPress} autoComplete="off" ref={this.inputRef}
             className="inputField"
             />
```

Sorry if this is a stupid question. I am not very knowledgeable about react yet.

**Comment by ginccc** [comment]
Any additional hint here, @alexmacarthur ? 

I am close to getting it all working, this is the only thing i haven't figured out yet..

**Comment by alexmacarthur** [comment]
Sorry for the delay with this! I'll need to do some testing and get back to you -- I thought it would carry props like that down automatically, but apparently not.

**Comment by alexmacarthur** [comment]
Digging into it, it looks like the only prop not getting transferred correctly is `autoFocus`. I wonder if this is something special about React in the way it handles focus state. I've found a couple things about it, like this:

https://davidwalsh.name/react-autofocus

And others who suggest setting auto-focus state by triggering it manually on `mount`: 

https://stackoverflow.com/a/28890330/3644967

Can you verify that `autocomplete` and `class` are getting set correctly? I see them correctly on my end.

**Comment by ginccc** [comment]
Hi Alex,

thank you for your suggestions, I have made it work now. I will soon contact you regarding a commercial license. 

Thank you for your support!

Best, Gregor

**Comment by ginccc** [comment]
Hi Alex,

thank you for your suggestions, I have made it work now. I will soon contact you regarding a commercial license. 

Thank you for your support!

Best, Gregor
