### ISSUE TITLE
Loop deleting first characters 

### ISSUE THREAD

**Issue by elliemanahi** [alexmacarthur/typeit#210]
I purchased from Code Canyon for a client site I'm working on (Squarespace) - I'm no developer, I'm a graphic designer so my coding knowledge is next to none. 

I've got it set up with 4 strings as per the code below. All works fine for the first few loops, then something happens at the end/start of the next loop and the first character of the first string isn't typed. So after another loop, it loses another character, eventually the first string is nearly completely gone. 

Now I know most people won't sit and watch the loop continuously to even notice, but it is noticeable when you go to another tab in your browser and come back a minute or two later and then the loop is still going, but the strings are reducing. 

There's probably a simpler script to achieve what I want, but I couldn't get the nextStringDelay to work. 

HOW I HAVE IT SET UP: 

<script src="https://cdn.jsdelivr.net/npm/typeit@7.0.1/dist/typeit.min.js"></script>

<script>
  new TypeIt('#element', {
  speed: 100,
  loop: true,
  loopDelay: 1500
})
  .type("Health & Wellbeing")
  .pause(1500)
  .delete(null)
  .pause(1000)
  .type("Optimal Function")
  .pause(1500)
  .delete(null)
  .pause(1000)
  .type("Performance")
  .pause(1500)
  .delete(null)
  .pause(1000)
  .type("Rehabilitation")
  .pause(1500)
  .delete(null)
  .go();

</script>

**Comment by alexmacarthur** [comment]
Sorry for the trouble with this! There was a bug recently fixed that addressed this issue, so I think you just need to use that latest version. Instead of the source link you're using, try this: 

```js
<script src="https://cdn.jsdelivr.net/npm/typeit@7.0.4/dist/typeit.min.js">
```

Let me know if that solves the problem. In the meantime, I'll update the site with that version so there's no confusion for anyone else.
