### ISSUE TITLE
Please link to github repo from website

### ISSUE THREAD

**Issue by zenflow** [alexmacarthur/typeit#212]
This project looks (don't want to swear, so) let's say "really good".

Please fix the marketing/documentation website.

![image](https://user-images.githubusercontent.com/3198597/86651466-8b92ed00-bfb1-11ea-9e56-b74cd8bc6783.png)

This appearance makes it look like closed-source commercial software.

I know it's open source & I read up and I know you actually have a free license for free software (❤️).

I guess that one small change on the site would reflect your product better and be a better image.

Cheers 🚀

**Comment by alexmacarthur** [comment]
Great suggestion! I have plans to revamp the site soon, and will likely include a change like this. Thx!
