### ISSUE TITLE
Typeit bug on Safari and iOS

### ISSUE THREAD

**Issue by alirezaashrafi** [alexmacarthur/typeit#215]
thanks for your great library 
but I have a big problem with typeit on ios 
words aren't separate in Farsi and Arabic
but this library type them separately char by char it works on android but not in ios
can you help me fix this issue?

<img width="735" alt="bug typeit" src="https://user-images.githubusercontent.com/25801966/90341811-0ff87700-e018-11ea-81d3-b82917372853.png">
<img width="735" alt="safari char problem" src="https://user-images.githubusercontent.com/25801966/90341831-2f8f9f80-e018-11ea-89cf-98ddf63e01f0.png">

**Comment by alexmacarthur** [comment]
Hi! Sorry for the delay... Unfortunately, this is an issue I'm not choosing to tackle right now, largely due to the complexity of tackling it for these types of languages. Closing for now.

**Comment by amiralidev** [comment]
Is there any update?
