### ISSUE TITLE
Can i change LICENSE if i make it opensource

### ISSUE THREAD

**Issue by asimo10** [alexmacarthur/typeit#216]
Hello! I like your typeit.js and i was wondering if I needed to use GPL-2 on my website that I use it on or I can use The-Unlicense. thank you. (Sorry if this question sounds stupid. I don't know much on LICENSES)

**Comment by asimo10** [comment]
...

**Comment by Kio-td** [comment]
@asimo10 You do not own the project, so you cannot change the License.
You must follow all the guidelines provided by the license.

If your project is commercial (If it makes money), then you must purchase a license from @alexmacarthur.

**Comment by asimo10** [comment]
Thanks for making it clear but I have already known it after all these days. Still thanks
