### ISSUE TITLE
Support prefers-reduced-motion for accessibility

### ISSUE THREAD

**Issue by joshwilsonvu** [alexmacarthur/typeit#217]
Thanks for the awesome project!

Some users, mostly those with vestibular motion disorders, set their devices to reduce non-essential motion in order to avoid discomfort. Modern browsers provide a way to detect this setting and reduce animations via the [`prefers-reduced-motion` media feature](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion).

It may be prudent to check `prefers-reduced-motion` and display only the final rendered value instead of the full animation if motion should be reduced. Now, I'm not 100% sure if TypeIt's animations can cause discomfort, but better safe than sorry. Developers can wrap TypeIt with this check manually, but it would be easier to build this check into the library.

I'm willing to provide a pull request to implement this feature. If there's already a way to precompute the final rendered value, please point me to it. Thanks!

**Comment by alexmacarthur** [comment]
Great callout! I'd prefer to keep the library slimmer and not build this in. As you mentioned, developers can choose to implement it themselves, so that's the path I'd recommend for now.
