### ISSUE TITLE
OPTIONS NOT WORKING: waitUntilVisible and lifelike

### ISSUE THREAD

**Issue by lordloadalot** [alexmacarthur/typeit#218]
Hi there, 

as mentioned before, two commands are not working in use with WP-Plugin and latest Elementor Pro Set Up:

A:  waitUntilVisible="true"( they are all firing at once after loading the page )
- - - - - - - - - - - - - - - - - - - - - - - - 
B:  lifelike="true"  ( Cannot see any effect, anything else to specify here ? )
- - - - - - - - - - - - - - - - - - - - - - - - 
I am using this method:  `[typeit waitUntilVisible="true" cursor="true" lifelike="true"] HERE COMES TEXT [/typeit]`

**Comment by alexmacarthur** [comment]
Issue resolved in v2.0.1 of the WordPress plugin: 

https://github.com/alexmacarthur/wp-typeit/releases/tag/v2.0.1
