### ISSUE TITLE
Request: support text before typing begins

### ISSUE THREAD

**Issue by redbrain** [alexmacarthur/typeit#219]
I'd like to use typeit to type the last few words of a sentence, and have the beginning of the sentence already there.
However, I can't figure out how to do that.
I'm assuming it's not currently supported; if so, could you consider adding support for it?
If it's already possible, could you tell me how to do so?
Thank you.

**Comment by zenflow** [comment]
I'm sure this supports having other text on the page that isn't touched.. did you try separating the text into a different `<span>`?

**Comment by redbrain** [comment]
I wanted it to be in the same element; however this is probably a better solution. Thanks.
