### ISSUE TITLE
target html tag needs to be "inline" or error

### ISSUE THREAD

**Issue by plagasul** [alexmacarthur/typeit#22]
This may not be exactly an issue, not sure.

I was getting an error: Cannot read property 'indexOf' of undefined(…) on loading the page with the simples typeIt examples.

It seems the problem was my target html tag was written as such

```
<div class="target">
</div>
```

instead of as such, which DOES work:

`<div class="target"></div>`

Is this expected behaviour for some reason? it kept me entertained and baffled for a while

thanks

**Comment by alexmacarthur** [comment]
Thanks, this will be addressed in the next build.
