### ISSUE TITLE
breakLines option doesn't seem to have any effect in typeit-react when declaring the strings as HTML 

### ISSUE THREAD

**Issue by empz** [alexmacarthur/typeit#229]
I'm trying to make a simple example with a list of words (that are already present in the HTML for SEO purposes) that gets written and replaced by the next one.

It was my understanding this could be achived by setting the option `breakLines: true` and separating them with line breaks.
I tried both natural line breaks and also <br /> elements but all I get is the words being written on top of the previous one.

Here's the Codesandbox: https://codesandbox.io/s/typeit-react-breaklines-option-6j75g

**Comment by sourcerer52** [comment]
You need to give multiple strings instead of one.

`      <TypeIt
        options={{ breakLines: false, strings: ["Developer","Engineer", "Writer"] }}
        element="h1"
      ></TypeIt>`

**Comment by empz** [comment]
> You need to give multiple strings instead of one.
> 
> ` <TypeIt options={{ breakLines: false, strings: ["Developer","Engineer", "Writer"] }} element="h1" ></TypeIt>`

I'm declaring the strings in the HTML for SEO purposes. If this way of declaring the strings is not compatible with the `breakLines: false` prop it should be stated in the readme.

**Comment by sourcerer52** [comment]
You're right, It doesn't work with HTML  ``<br/>`` when it is mentioned in the docs that :

>It's also possible to define multiple strings by separating them with a ``<br>`` tag.

**Comment by sourcerer52** [comment]
@alexmacarthur the ``_maybePrependHardcodedStrings`` function returns a single string, even in case of innerHTML being separated by ``<br />`` tag, maybe it needs to be split to form an array of strings before returning?

`` existingMarkup.trim().split('<br>');``

or some other way that ``constructQueueFromNodes`` returns the ``characterObjects``

I tried the first method and breakLines works with ``<br />``; however, I'm not sure if it's the optimal way.

**Comment by alexmacarthur** [comment]
Thanks for letting me know about this! A fix has just been merged. Unsure when it'll go out, however. Stay tuned.
