### ISSUE TITLE
[request] type method should take function

### ISSUE THREAD

**Issue by braco** [alexmacarthur/typeit#231]
It would open up some nice use cases if type() allowed functions as well as strings.

```
.type(() => `some dynamic text here: ${var}`)
```

**Comment by alexmacarthur** [comment]
Done! It's been merged into master, and will be released in the next version.. unclear of when that will be exactly. Thanks for suggesting this.

**Comment by braco** [comment]
Hey @alexmacarthur, it seems like the .type() function param is run when .go() is called, is that correct?

This feature would be more useful if the function was called when that .type() was about to execute, eg:

```
 new TypeIt().pause(10000).type(() => { console.log('hi') }).go()
```

^ Currently this will `console.log('hi')` immediately, whereas it should only be after the pause() is completed

The use case for this is accessing variables that might not be available immediately.
