### ISSUE TITLE
[request] move to #ID

### ISSUE THREAD

**Issue by braco** [alexmacarthur/typeit#232]
I'm finding the move() method difficult since it needs different param values depending on what the text is – if the text is dynamic, the strings need to be manually length measured.

Having something like this would help a lot:

```
.type('<span id="foo">....</span>')
.move('#foo', { cursor: 'start' })
.move('#foo', { cursor: 'end' })
```

`cursor` defining if it's going to the beginning or end of the element

**Comment by alexmacarthur** [comment]
I friggin' love this idea.

**Comment by alexmacarthur** [comment]
Merged! https://github.com/alexmacarthur/typeit/pull/244

Unclear when this will be, but you'll see it in the next released version.

**Comment by braco** [comment]
Just saw these updates, thanks!
