### ISSUE TITLE
move not working when cursor is false *bug*

### ISSUE THREAD

**Issue by sappron** [alexmacarthur/typeit#236]
If you use move when cursor is false, move function dosen't work
example:
`new TypeIt("#intc", {
  speed: 50,
  startDelay: 900,
  cursor:false
})
  .type("the mot versti", {delay: 100})
  .move(-8, {speed: 25, delay: 100})
  .type('s')
  .move('START')
  .move(1, {delay: 200})
  .delete(1)
  .type('T')
  .move(12, {delay: 200})
  .type('a', {delay: 250})
  .move('END')
  .type('le animated typing utlity')
  .move(-4)
  .type('i')
  .move('END')
  .type(' on the internet', {delay: 400})
  .delete(8, {delay: 600})
  .type('<em><strong>planet.</strong></em>')
  .go();`

**Comment by alexmacarthur** [comment]
Thanks for reporting this! Just merged in a [fix](https://github.com/alexmacarthur/typeit/pull/241) for this. Unfortunately, I'm not quite sure when the next release will be... I'm in a weird state with some other larger changes going on.
