### ISSUE TITLE
Interrupting a typeIt call with another typeIt call: double callback ?

### ISSUE THREAD

**Issue by plagasul** [alexmacarthur/typeit#25]
(Probably NOT an issue, but a difference between expected and actual behaviour)

I am using typeit to write text that when clicked, asks typeIt to write another text.

All texts are written in the same div. So when text1 is clicked, text2 overwrites it.

BUT, if text1 is clicked BEFORE it has been typed completely, AND there is a callback, it seems to be executed, WHILE text2 is being typed.

The expected behaviour would be that launching a 2nd typeIt call would completely stop a 1st typeIt call, including the callback.

I guess this is not really what is happening.

Would there be a way to completely abort a typeIt call, to be sure this does not happen?

thanks

**Comment by plagasul** [comment]
Alex. Closed because not an issue? 
thanks

**Comment by alexmacarthur** [comment]
Sorry about that, @plagasul -- I thought it was a non-issue, but after digging into it a little further, I do see the issue, and I agree it that it should be fixed. 

I've found the problem -- it will be resolved with the next build. 

Thanks for your patience!

**Comment by alexmacarthur** [comment]
Hi, @plagasul -- Letting you know a new release is out that resolves your issue. 

https://github.com/alexmacarthur/typeit/releases/tag/v4.3.0

Thanks for using TypeIt! If you don't mind staring and/or sharing the project, I'd really appreciate it!

**Comment by plagasul** [comment]
Hello Alex and thank you, but I am not sure this is working in all situations.

Here is a jsfiddle, please watch the console:

https://jsfiddle.net/plagasul/a5db9ekz/

What I am trying to show is that calling a second typeit on the same element before the first typeit call has finished, may result in the first typeit callback being invoked nevertheless. And I think this is related to the time it takes for typeit to cancel the previous call.

In my example, the second call is invoked quite near the end of the first call. If I reduce the speed or wait less to call the second typeit, it works as expected. 

thanks
