### ISSUE TITLE
[request] delete to location

### ISSUE THREAD

**Issue by braco** [alexmacarthur/typeit#253]
It would be nice if .delete could take a similar signature to .move:

```
const instance = new TypeIt('#el', {})
   .type("Hello, <strong class='t'>friend!</strong> Hope you are well.");
   .delete(".t", { to: 'end' })
```

which would yield `Hello, friend!`

or maybe `.deleteTo()`?

Anything that allows fluent-style "do this action up to this marker" would be helpful, it's difficult to work by character count.

**Comment by alexmacarthur** [comment]
Good timing.. just-released v8 introduces this exact feature! I just tried your code snippet and it yields the result you suggested. 

More on that here: 
https://typeitjs.com/docs/vanilla/instance-methods#delete
