### ISSUE TITLE
[request] pattern for manually looping?

### ISSUE THREAD

**Issue by braco** [alexmacarthur/typeit#254]
Don't think this works – is there a way to functionally loop after completion without wiping everything out with a new instance?

```
new TypeIt("#element", {
  afterComplete: async (step, instance) => {
      instance.type('something new').go()
  } 
});
```

Doesn't work with `step.type`, and `instance` is undefined for me.

The use case for this is that sometimes you might want to use vars/patterns that aren't immediately available. For me that's a slowly resolving promise that may or may not be successful by the time the first loop is done.

**Comment by alexmacarthur** [comment]
Hi, @braco -- let me know if the new `.flush()` method doesn't help you out (if you still need it). `.go()`, can be called only once per instance, but `.flush()` can animate any number of actions arbitrarily, even after instantiation. The characters it types just won't be stored to the instance's queue: 

```js
const element = document.getElementById('type');

new TypeIt(element, {
  strings: 'hi,',
  afterComplete: async (instance) => {
    instance.type(' pal.').flush();
  } 
}).go();
```

Example here: https://codepen.io/alexmacarthur/pen/KKQbaGX
