### ISSUE TITLE
Allow add text dynamically?

### ISSUE THREAD

**Issue by naecoo** [alexmacarthur/typeit#259]
After calling `go` method, can i add some text dynamically?

**Comment by alexmacarthur** [comment]
Hi, @naecoo -- I just published a version tonight that introduces a `.flush()` method, which allows you to do this. It's nice for running one-off animations after you use `go()`, without modifying any animation you've already built. 

https://github.com/alexmacarthur/typeit/releases/tag/v8.5.3

Rudimentary demo here: 

https://www.typeitjs.com/demos/flush

Hope that helps!
