### ISSUE TITLE
Font size jumps on ios

### ISSUE THREAD

**Issue by adamjw3** [alexmacarthur/typeit#26]
Hi when i have the following and once its deleted the font size jumps.

here is my code

` <span class="t1"><span class="text t1">Lorem ipsum</span></span>
    <br>
    <br>
    <span class="t2"><span class="text-1 t2">Lorem ipsum</span></span>`

`$('.text').typeIt({
                        cursor: false,
                        speed: 400,
                        lifeLike: true,
                        autoStart: false,
                        startDelete: true
                    })
                    .tiSettings({speed: 300})
                    .tiType('I am typing slowly,')
                    .tiSettings({speed: 100})
                    .tiType('but now I am typing pretty fasst')
                    .tiSettings({speed: 300})
                    .tiDelete(2)
                    .tiType('t!');`

`$('.text-1').typeIt({
                        cursor: false,
                        speed: 400,
                        lifeLike: true,
                        autoStart: false,
                        startDelete: true
                    })
                    .tiSettings({speed: 100})
                    .tiType('I am typing slowly,')
                    .tiSettings({speed: 100})
                    .tiType('but now I am typing pretty fasst')
                    .tiSettings({speed: 300})
                    .tiDelete(2)
                    .tiType('t!');`

**Comment by alexmacarthur** [comment]
Hi, @adamjw3. I'm unable to replicate this in any browser, nor on a mobile device. Can you confirm it's still an issue, and possibly send me your setup?
