### ISSUE TITLE
breaks when used multiple times

### ISSUE THREAD

**Issue by jonathanstanley** [alexmacarthur/typeit#270]
thanks for the `typeit-react` library!

when attempting to add a second one, it fails

```JSX
<div>
  <TypeIt>text1</TypeIt>
  <TypeIt>text2</TypeIt>
</div>
```
... the above would output "text2" for both.

see demo of the problem:
https://codesandbox.io/s/shy-bash-9ougl?file=/src/App.js

**Comment by alexmacarthur** [comment]
Thanks for letting me know about this! Fixed in [v2.1.1](https://github.com/alexmacarthur/typeit/releases/tag/typeit-react%402.1.1).
