### ISSUE TITLE
Chrome translators can't translate typeit texts

### ISSUE THREAD

**Issue by t41372** [alexmacarthur/typeit#273]
#### Description
Browser translator on chrome produces garbled texts when translating typeit texts.
The translator on Microsoft Edge seems to work fine. I haven't tested it on any other browser.

For example, when translating typeitjs.com:
the heading:
`The most versatile typing utility on the planet.`
would produce a translation:
`Ť ħ Ë 米直徑：小號噸 v Ë ř小號一噸我升é 噸ý p我Ñ克 ü噸我升我噸ý ö Ñ 噸ħ Ë p升一Ñ ë噸。`
when the correct translation should be:
`地球上最通用的打字工具。`

#### To Reproduce
Use the Chrome browser translator to translate texts generated from Typeit

![image](https://user-images.githubusercontent.com/36402030/146715211-38a9c40d-8627-4293-8baf-be691a848df5.png)

**Comment by alexmacarthur** [comment]
Hi, thanks for letting me know about this. It's possible that the way the library is generating text nodes could impact the way that translation tool works. However, that could easily be something that totally upends how TypeIt functions, so I won't be doing anything about this for now.
