### ISSUE TITLE
.tiDelete() not working

### ISSUE THREAD

**Issue by livevie** [alexmacarthur/typeit#28]
hi Alex,

there is one problem with .tiDelete():

i wrote this code: 
.tiType('<span class="hashtag"></span><span class="text1">dort </span><span class="text2">wo </span><span class="text3">es</span><span class ="text4"> zählt</span>')
.tiPause(2000)
.tiDelete()

and .tiDelete is not working in this case. its just fade to the next .tiType without the delete effect.

please help :)

thanks

**Comment by livevie** [comment]
fixed it .. :)

**Comment by alexmacarthur** [comment]
Hi, @livevie -- glad you got it working! Let me know if you have any other issues in the future.
