### ISSUE TITLE
No index.d.ts in dist with version 2.3.2

### ISSUE THREAD

**Issue by sereyn** [alexmacarthur/typeit#285]
![image](https://user-images.githubusercontent.com/33748126/156009020-3e18f39e-f2b3-4d27-9231-6a1eb370f2fa.png)

And my project that uses Create React App with typescript is complaining:

```
Failed to compile.

/Users/.../src/components/HomePage/index.tsx
TypeScript error in /Users/.../src/components/HomePage/index.tsx(10,20):
Could not find a declaration file for module 'typeit-react'. '/Users/.../node_modules/typeit-react/dist/index.umd.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/typeit-react` if it exists or add a new declaration (.d.ts) file containing `declare module 'typeit-react';`  TS7016

     8 | import _ from 'lodash'
     9 | import { useDispatch } from 'react-redux'
  > 10 | import TypeIt from 'typeit-react'
       |                    ^
    11 | import wikipediaLogo from 'res/logo/wikipedia-notext.png'
    12 | import wikidataLogo from 'res/logo/wikidata-notext.png'
    13 |
```

My `package.json` requires `typeit-react` with version `^2.2.0`. Npm resolved it with version `2.3.2` (which should be fine). I solved the problem by forcing the version like that: `"typeit-react": "2.2.0"` (removed the `^` to force the version) so I guess the problem is with the version `2.3.2`.

**Comment by alexmacarthur** [comment]
Thanks for letting me know about that! Not sure how those fell through the cracks. v2.3.3 fixes the issue. Let me know if you hit anything else.
