### ISSUE TITLE
loop not working with html content

### ISSUE THREAD

**Issue by alireza23** [alexmacarthur/typeit#286]
`<span style="red">typeitjs</span> is the best!`

setting  both the loop and html true, breaks the loop.

**Comment by alexmacarthur** [comment]
Hi! I'm not able to replicate this issue with the following setup. If it's still an issue, would you mind providing a CodePen or some other example? 

```js
new TypeIt("#example", {
  speed: 50,
  strings: '<span style="red">typeitjs</span> is the best!',
  loop: true, 
  html: true
}).go();

```

**Comment by alireza23** [comment]
thanks for your reply and thanks again for the plugin.
apparently I was not using the latest version of typeit!
