### ISSUE TITLE
When using <h1>,<h2>, etc. tags weird padding problems occur

### ISSUE THREAD

**Issue by GrayTurtle** [alexmacarthur/typeit#29]
Hi Alex,
I'm just starting out with web dev, so I'll try my best to explain!
When I use the h1, h2, etc. tags, it creates some weird padding problems. It would create unnecessary padding when there is a new line. The cursor also starts out at the beginning of the next line, not at the end of the current line that is being typed out.
This is what it would do:
![typeit problem](https://cloud.githubusercontent.com/assets/16218882/21164714/7ead00f6-c160-11e6-9cba-382e2e197189.PNG)

This is the code:
```		
               <script>
			var firstLine = "<h1>Hi, I'm <strong>John Tran</strong></h1>";
			var secondLine = "<h2>Developer | Engineer | h@ck3r</h2>";
			$('.type-it').typeIt({
				strings: [firstLine, secondLine]
			});
		</script>
```

I went around this by deleting the tags and using css to change the font size. It works perfectly now. http://johntran.me is the website that I'm working on with this.
I haven't tried using other tags like p1, but once I got the css working, so I didn't really bother.
Even though I went around this, I just wanted to bring this problem up! Thank you!

**Comment by alexmacarthur** [comment]
Hi, @GrayTurtle. Sorry, I'm not able to replicate this locally. Perhaps it was a styling issue unique to your environment? Closing do to that likelihood and how old this issue is (sorry about the delay!).
