### ISSUE TITLE
[question] double line break instead of single line break

### ISSUE THREAD

**Issue by avianion** [alexmacarthur/typeit#293]
currently the library takes <br> elements, no matter how many there are, and turns them into a single line break.

but what if we want it to be a double line break, for presentation sake?

**Comment by alexmacarthur** [comment]
Hi - I'm not sure I follow. You should be able to insert as many line breaks as you want using the `.break()` method, like so:

```js
new TypeIt("#element")
  .type("one")
  .break()
  .break()
  .type("two")
  .go();
```

See demo here: 
https://codepen.io/alexmacarthur/pen/OJzebVa?editors=1010

Does that help?
