### ISSUE TITLE
Stalls for a while between loops

### ISSUE THREAD

**Issue by elvismdev** [alexmacarthur/typeit#297]
Hello, in my current implementation I need to loop trough different strings that are typed and deleted infinitely at the same intervals of times (using `.pause(1000)`). 

However, even if I have `loopDelay: 0` in the options, it takes a few seconds more than expected to start the loop of these strings again, making it feel stalled for a bit without any text typing.

My expectations are that it should just keep going over and over at the same `.pause(1000)` intervals I'm defining after each string typed.

Here my current code:
```javascript
document.addEventListener("DOMContentLoaded", function () {
    new TypeIt("#typeItElement", {
      speed: 150,
      loop: true,
      loopDelay: 0,
      startDelay: 1000,
      lifeLike: false,
    })
      .type("ABC")
      .pause(1000)
      .delete()
      .type("DEF")
      .pause(1000)
      .delete()
      .type("GHI")
      .pause(1000)
      .delete()
      .type("JKL")
      .pause(1000)
      .delete()
      .type("MNO")
      .pause(1000)
      .delete()
      .type("PQR")
      .pause(1000)
      .delete()
      .go();
});
``` 

What I'm getting wrong in my current implementation? Or I'm understanding incorrectly how it works the `loopDelay` option?

**Comment by alexmacarthur** [comment]
Thanks for letting me know about this, @elvismdev -- there's definitely something odd going on here. I'm looking into it now.

**Comment by alexmacarthur** [comment]
@elvismdev Found the issue and released a fix. v8.5.4 should take care of you. Thanks again for letting me know!

https://github.com/alexmacarthur/typeit/releases/tag/v8.5.4

**Comment by elvismdev** [comment]
> @elvismdev Found the issue and released a fix. v8.5.4 should take care of you. Thanks again for letting me know!
> 
> https://github.com/alexmacarthur/typeit/releases/tag/v8.5.4

Amazing, thanks @alexmacarthur !
