### ISSUE TITLE
Typescript type definitions do not allow usage as described in the docs

### ISSUE THREAD

**Issue by juzerzarif** [alexmacarthur/typeit#299]
Using typeit v8.5.4 ([codesandbox](https://codesandbox.io/s/modern-sky-vp91ek?file=/src/index.ts))

The type definition for the default export is the [`TypeItInstance`](https://github.com/alexmacarthur/typeit/blob/master/packages/typeit/src/types.ts#L1) which is not constructible signature and so the typescript compiler throws an error when doing this in strict mode:
```typescript
const typeit = new TypeIt(...) // ❗️'new' expression, whose target lacks a construct signature, implicitly has an 'any' type.ts(7009)
``` 

`TypeItInstance` also just returns `void` so the types for the actual returned typeit instance don't seem to be defined at all. I see the source code is written in typescript but using the constructor function pattern instead of an actual class. I'm not sure why that is (maybe a migration from JS to TS happened?) but if the source code were converted to a class it would automatically generate the correct types at build time.

I'm not sure if that's a rewrite that's in the pipeline or if it's even on the table but in the meantime at least I think the type definitions should be fixed to reflect the actual API for the library. I'd be willing to put up a PR to update the types for the core package unless I'm missing something here.

**Comment by cary-hu** [comment]
I face this problem too, there was a workaround: 
```
new (TypeIt as any)(hero, {
    strings: ["Hello, world!"],
    speed: 100,
    breakLines: false,
    loop: true,
  }).go();
```

**Comment by alexmacarthur** [comment]
Thanks for reporting this! I should be able to knock out a fix tonight.

**Comment by alexmacarthur** [comment]
Welp, that didn't go as planned. 😆 

> I'm not sure why that is (maybe a migration from JS to TS happened?)

You're right about this. TypeIt was initially written in plain JS (and using classes), and since then, it's gone through quite a few change, with this being one of the side effects. 

For now, I'm planning on leaving this as-is until I'm prepared to release the next major version. Until then, as @cary-hu suggested, please manually type it as `any`. Not ideal, but I'd like to do it the right way and also not introduce any breaking changes right now. 

Thanks a ton for reporting this!

**Comment by mwskwong** [comment]
Too bad, for me, I just add `@ts-ignore` while using `new TypeIt` for now.

**Comment by shmolf** [comment]
👋 Just wanted to check when the next major release that'd include a fix, would be released.

**Comment by alexlafroscia** [comment]
In case anyone else is looking to resolve this, I ended up using a [`pnpm` patch](https://pnpm.io/cli/patch) (though a [`yarn` patch](https://yarnpkg.com/features/patching) or [`patch-package`](https://www.npmjs.com/package/patch-package) should work too) to override the built-in `index.d.ts` with the following contents. This seems to provide type definitions that match what the library's documentation describes:

```ts
import { Options } from "./types";

interface ActionOptions {
  delay?: number;
  instant?: boolean;
}

type Status = "started" | "complete" | "frozen" | "destroyed";

declare class TypeIt {
  constructor(element: string | HTMLElement, options?: Options);

  /* == Chainable Methods == */

  type(input: string | (() => string), options: ActionOptions): TypeIt;

  delete(
    numberToDelete?: number | string | (() => number | string),
    actionOptions?: ActionOptions
  ): TypeIt;

  pause(
    milliseconds: number | (() => number),
    actionOptions?: ActionOptions
  ): TypeIt;

  break(actionOptions?: ActionOptions): TypeIt;

  options(options: Options, actionOptions?: ActionOptions): TypeIt;

  empty(actionOptions?: ActionOptions): TypeIt;

  move(
    movementArg: number | string | null | (() => string | number | null),
    actionOptions?: ActionOptions
  ): TypeIt;

  exec(func: () => any, actionOpts?: ActionOpts): TypeIt;

  /* == Non-Chainable Methods == */

  destroy(removeCursor?: boolean): void;

  reset(): void;

  freeze(): void;

  unfreeze(): void;

  is(status: Status): void;

  /* == Kicking off an Animation == */

  go(): void;

  flush(callback?: () => any): void;
}

export default TypeIt;
```
