### ISSUE TITLE
What about loop?

### ISSUE THREAD

**Issue by subirpal** [alexmacarthur/typeit#3]
Thanks for the awesome lightweight plugin. It would be best if there is a option for looping string.

**Comment by alexmacarthur** [comment]
Great idea I've heard from someone else too. Hoping to make it a reality soon!

**Comment by fashiontv1** [comment]
You can loop by code:
function loop(){
            $('#tlt').typeIt({
                whatToType: ["THIS MY TEXT 1", "THIS MY TEXT 2"],
                typeSpeed: 200,
                breakLines: false,
                showCursor: false
            }, function () {
                loop();
            });
        }
        loop();

**Comment by subirpal** [comment]
Great! Thanks man :+1:

**Comment by alexmacarthur** [comment]
Hey, @subirpal, @fashiontv1 -- Just pushed new release that has this feature built in. Let me me know of any suggestions/issues!

https://github.com/alexmacarthur/typeit/releases/tag/2.0.0

**Comment by Jar36** [comment]
Alex, 
What's is the proper way to use the loop() option. I am wanting to type a string delete then type a different string delete and then loop. 

Any tips?

**Comment by alexmacarthur** [comment]
Hi, @Jar36 -- This should do the trick. It'll type a string, delete it, type the next, and then delete that and start over again. For more options on controlling the pausing for all of that, see the docs: [typeitjs.com/docs](https://typeitjs.com/docs).

```js
const yourInstance = new TypeIt('#element', {
   strings: ['My first string.', 'My second string.'],
   breakLines: false,
   loop: true
});
```

**Comment by Jar36** [comment]
Thank you @alexmacarthur! I really appreciate you taking the time to help me out.
