### ISSUE TITLE
Async loading without require.js

### ISSUE THREAD

**Issue by Enelar** [alexmacarthur/typeit#30]
I am expecting this library to bind jQuery instance on runtime. Because at the time i actually requests it - it present already. I am referencing jQuery with `async`, and this library with `async defer` attributes.

And sometimes, depending on connection conditions, because this library smaller, it got loaded first, and execution aborts. Not jQuery is present.

I am unable to get this usable without bulky requirejs. Outdated readme suggests use blocking mode (sic!).

**Comment by alexmacarthur** [comment]
Hi, @Enelar -- 

I'm not an expert on loading scripts using `async` and `defer` attributes, but from my understanding, you wouldn't need to use them if you load your scripts in the footer. This way, you can explicitly set the load order, and not have to worry about render blocking. 

Do you think that'd be a possibility for your project?

**Comment by Enelar** [comment]
@alexmacarthur, well nope. I managed to add `<script>` tag whenever i feel good for it. If you read any "60fps" guide, it always shows that any JS can affect smoothiness of the page. And load time, its very risky time frame for scrolling. You also have style calculations etc. So whenever it possible, youre welcome do give air gasp for browser.

That's why i like to push every script at the top (in `<head>`), and allow browser download / compile resources in different thread. Which wouldn't affect "drawing" thread. On start time, most of the time spend on parsing / creating objects. 

BTW im also utilizing H2 push, for async CSS calculate in chrome.

And last thing, i noticed that you made cursor blinking animation in JS (CPU).
Consider use `opacity 0/1` and `transition: opacity 0.5s`.

**Comment by alexmacarthur** [comment]
Great feedback. I do have plans on removing the jQuery dependency. Will also take into account your feedback regarding blinking animation. Thanks!
