### ISSUE TITLE
`startDelete` only deletes the last character of the hardcoded text

### ISSUE THREAD

**Issue by mwskwong** [alexmacarthur/typeit#301]
Minimal reproduction:
[![Edit quirky-haze-o3og12](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/quirky-haze-o3og12?fontsize=14&hidenavigation=1&theme=dark)

Edit.
Seems related to
https://github.com/alexmacarthur/typeit/blob/bf3adc8079100373325d5bc3a44d59595de25e29/packages/typeit/src/index.ts#L325

Why only remove one single character instead of doing `_getAllChars().forEach(removeNode)`

**Comment by alexmacarthur** [comment]
Thanks for this! I'll check out that PR in the next day or two.
