### ISSUE TITLE
Array value of `nextStringDelay` does opposite of what the document suggests

### ISSUE THREAD

**Issue by mwskwong** [alexmacarthur/typeit#303]
Let say you specify `nextStringDelay: [1500, 375]`. The document suggests it should work as follow:
```
wait 1500ms --> type --> wait 375ms --> delete
```
While the actual behavior is as follows:
```
wait 375ms --> type --> wait 1500ms --> delete
```

Minimal reproduction:
[![Edit frosty-mendel-jkkn3z](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/frosty-mendel-jkkn3z?fontsize=14&hidenavigation=1&theme=dark)

**Comment by alexmacarthur** [comment]
This is my fault for leaving confusing documentation. The `nextStringDelay` value controls the pausing prior to and after typing each string, _with exception to the initial string being typed_, which is configured by the `startDelay` option. Consider the following example: 

```js
new TypeIt({
   strings: ["A", "B", "C"],
   nextStringDelay: [3000, 1000],
   startDelay: 5000
}).go();
```

That would type out like this: 

```
pause 5000ms --> type "A" --> pause 3000 --> pause 1000 --> type "B"
```

I admittedly don't love this particular feature due to the confusion it sends, and I'm considering doing away with its current implementation in a future release.

**Comment by mwskwong** [comment]
Also, another thing is when you enable `startDelete` and `loop`, after a cycle is completed, an extra `delete` seems to play out.
This extra `delete` appears to be the initial delete that is supposed to delete the hard-coded text (since `startDelete` is enabled). Since there is no text at this point, it just causes additional delay.

i.e. this is how it currently works:
```
delete hard code text --> type line 1 --> delete line 1 --> type line 2 --> delete line 2 --> delete hard code text --> type line 1 --> repeat...
```

**Comment by alexmacarthur** [comment]
@mwskwong Sorry, I'm not able to replicate this (using the latest version). Can you drop an example instance you're seeing it for?

**Comment by mwskwong** [comment]
> @mwskwong Sorry, I'm not able to replicate this (using the latest version). Can you drop an example instance you're seeing it for?

I updated the CodeSandbox in the OP. Pay attention to the delay between `line 1` and `line 2` and compare that with others.

**Comment by alexmacarthur** [comment]
@mwskwong Ah, I notice it now. I believe that's due to the default value for the `loopDelay` option. If you set `loopDelay: 0` when creating the instance, that delay is removed.

**Comment by mwskwong** [comment]
Not quite, it doesn't seem to be how it works. It will act quite wierd when you set a longer `nextStringDelay` and make `loopDelay: 0`.

e.g.
[![Edit tender-black-k6lb3j](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tender-black-k6lb3j?fontsize=14&hidenavigation=1&theme=dark)

**Comment by sreuter** [comment]
The values work the other way around for me as well. The first value is a delay after something has been typed (before it starts to delete), and the second value is a delay after the previous string has been deleted (and before it's typed again).

**Comment by alexmacarthur** [comment]
I've finally come around on this and get the confusion. I've updated the documentation on this. No changes will be made to the library itself as of now.

https://www.typeitjs.com/docs/vanilla/usage/#configuration-options
