### ISSUE TITLE
<a></a> doesn't work with ""

### ISSUE THREAD

**Issue by GrayTurtle** [alexmacarthur/typeit#31]
Hey Alex,

typeit doesn't work when I try to do a link with double quotations. For example,
`<a href="link">blah</a>` stops it from working. However, if I use single quotations, it works fine.

**Comment by millansingh** [comment]
If you are using double quotes for the argument you pass to the TypeIt function, then you need to use single quotes for anything inside it, or vice-versa. This is a javascript issue, not a TypeIt issue. For example:

`tiType("<a href='link.com'>Link</a>")`

should work.

`tiType("<a href="link.com">Link</a>")`

should fail. Javascript is interpreting that last example as multiple string arguments with incorrect characters in between.

Does that solve the issue?

**Comment by GrayTurtle** [comment]
Yes! Thank you!
