### ISSUE TITLE
Animations on iOS/iPadOS are not smooth

### ISSUE THREAD

**Issue by jesusalber1** [alexmacarthur/typeit#311]
Animations are not smooth on iOS devices, moving the cursor or updating the text makes it overlap for a moment, and then it's automatically fixed. It also happens on iPad devices, so it's possible that it has something to do with how WebKit renders the content. It works well on macOS though.

https://user-images.githubusercontent.com/3829533/174449122-e870c086-e1d1-48b2-98bc-e7bd8377105f.MP4

**Comment by alexmacarthur** [comment]
Thanks for letting me know about this! Oddly enough, it doesn't seem to be happening on *some* iOS devices. I'll have to dig in.

**Comment by alexmacarthur** [comment]
@jesusalber1 This is fixed in the latest release. Thanks again for letting me know about it!

**Comment by jesusalber1** [comment]
That's awesome! Many thanks for the fix @alexmacarthur 🤩
