### ISSUE TITLE
[QUESTION] (ReactJS + TypeScript) How can I remove the cursor after text finished on React Component?

### ISSUE THREAD

**Issue by MiraiMindz** [alexmacarthur/typeit#327]
I'm having trouble with the cursor using TypeScript+ReactJS and the TypeIt React Component

when I use this code:

```js
<TypeIt
    getBeforeInit={(instance: any) => {
    instance.type('Sample Text').go();
    return instance;
    }}
    options={{
    waitUntilVisible: true,
    speed: 200,
    }}
/>
```

It produces this output:

https://user-images.githubusercontent.com/78761663/190931718-dfe080f5-70bd-4aef-90af-1c18b4cd7cc7.mp4

but when I use this code:

```js
<TypeIt
    getBeforeInit={(instance: any) => {
    instance.type('Sample Text').go();
    return instance;
    }}
    options={{
    waitUntilVisible: true,
    speed: 200,
    }}
    getAfterInit={(instance: any) => {
    instance.destroy();
    return instance;
    }}
/>
```

I get this output:

https://user-images.githubusercontent.com/78761663/190931787-1a37d08b-8827-496a-a331-bac100e1e604.mp4

How can I manage to make the cursor disappear only when I stoped typing on the react component?

**Comment by alexmacarthur** [comment]
Hi, @MiraiMindz! Sorry for the huge delay with this. To make the cursor disappear after typing is completed, you can use the `afterComplete` callback.

https://www.typeitjs.com/docs/vanilla/usage#callback-methods

```tsx
    <TypeIt
      getBeforeInit={(instance: any) => {
        instance.type('Sample Text').go();

        return instance;
      }}
      options={{
        waitUntilVisible: true,
        speed: 200,
        afterComplete: (instance) => {
          instance.destroy();
        }
      }}
    />
```

Or, if you want to manipulate the cursor directly, you can do this: 

```tsx
    <TypeIt
      getBeforeInit={(instance: any) => {
        instance.type('Sample Text').go();

        return instance;
      }}

      options={{
        waitUntilVisible: true,
        speed: 200,
        afterComplete: (instance) => {
          const cursor = instance.getElement().querySelector('.ti-cursor');

          cursor.remove();
        }
      }}
    />
```
