### ISSUE TITLE
TypeError: Cannot read property 'useRef' of null with next js. 

### ISSUE THREAD

**Issue by GautierArcin** [alexmacarthur/typeit#328]
Hello,

I just updated my blog from next 11.x to 12.x. I'm using your awesome library you developed for my blog (on my main page, [you can check it out here](https://www.gautierarcin.com/).

But after the migration, it seems that I have this error: 

![image](https://user-images.githubusercontent.com/34534254/194768069-01189d17-c5f1-43bd-a98b-fc05b65675e6.png)

Even with a default TypeIt component ` <TypeIt>This will be typed in a `span` element!</TypeIt>`.

Do you have any idea where it might come from ?

Kind regards,

Gautier

**Comment by jahvi** [comment]
I'm having the same issue as well, did you find a workaround @GautierArcin by any chance?

**Comment by GautierArcin** [comment]
@jahvi Sadly not at all. 🫤

Keep me posted if you find any workaround! I'll be very interested

**Comment by engin-can** [comment]
Same issue here!

**Comment by alexmacarthur** [comment]
Sorry for the delay, everyone. That's a very odd error... I'm using Next for my site, and having no issues with it (v13 as well). I did make a small tweak to how refs are used in the typeit-react package tonight (v2.6.1). If you don't mind, please try updating to that version and let me know if you're still having issues. I'm also curious: 

* are you seeing this issue in development + production mode? Or only one of them? 
* are you using Next's new app directory? 
* Are you statically generating your app, or using SSR? 

Thx!

**Comment by alexmacarthur** [comment]
I just hit this while setting up a Docusaurus site. Gonna dig in more!

**Comment by alexmacarthur** [comment]
@GautierArcin @jahvi @engin-can This should now be fixed in v2.6.4 of the React component! I had some inconsistent hook imports and some overly-strong `peerDependency` constraints that were causing this. Please let me know if you see any other issues.
