### ISSUE TITLE
Countup- Countdown-Effect?

### ISSUE THREAD

**Issue by nicmare** [alexmacarthur/typeit#329]
Nice Plugin! Purchased it although i have no recent use for it but i like how it works and that a Gutenberg block is available. I am sure, i need it soon.

Are there any plans to add simple Countdown/ Countup number effects they starting to animate when they are in the viewport? Like "we have >100< happy clients" or ">1000< installs and still growing"…

like on your page https://macarthur.me/dashboard

**Comment by nicmare** [comment]
<img width="66" alt="image" src="https://user-images.githubusercontent.com/898582/197170521-58c1e061-65e4-465a-b2d6-bcd8a2a60b91.png">
you are using it on your own blog too

**Comment by alexmacarthur** [comment]
Hi, @nicmare -- thanks! No plans for adding that to TypeIt right now. The library I'm using to do that knocks it out of the park. Try it out if you have a need for something similar!

https://inorganik.github.io/countUp.js/
