### ISSUE TITLE
How to loop among only a few particular strings?

### ISSUE THREAD

**Issue by Reservations** [alexmacarthur/typeit#33]
Basically, I want to type " I am a _____" and cycle through words to fill in the blank afterwords, deleting just the last word and retyping it.

Here is what I currently have:
	
     
```
.tiType('I am a ')
.tiType("student.")
.tiPause(3000)
.tiDelete(8)
.tiType("programmer.")
.tiPause(3000)
.tiDelete(11)
.tiType("hobbyist.")
.tiPause(3000)
.tiDelete(9)
```

I want to keep the "I am a" part and only continuously cycle (loop) through the words that fill in the blank. Is there a way to do this? Thank you.

.

**Comment by frazerf** [comment]
Have two instances of typeIt. One to type the "I am" bit and then add a second, with a delay that starts after the first instance of typeIt, that cycles through the "student, programmer, etc" option using a loop.

`$('#example').typeIt({
  speed: 50,
  autoStart: false,
  loop: true
})
.tiType("student.")
.tiPause(3000)
.tiDelete(8)
.tiType("programmer.")
.tiPause(3000)
.tiDelete(11)
.tiType("hobbyist.")
.tiPause(3000)
.tiDelete(9)`

**Comment by alexmacarthur** [comment]
Not an issue with the
