### ISSUE TITLE
Using it with webpack2

### ISSUE THREAD

**Issue by VarunBatraIT** [alexmacarthur/typeit#34]
webpack2 config is below.
```
const path = require('path');
const webpack = require('webpack');
module.exports = {
    context: path.resolve(__dirname, './'),
    entry: {
        app: ['./public/js/main.jsx']
    },
    output: {
        path: path.resolve(__dirname, './public/js/'),
        filename: 'main.js'
    },
    plugins: [
        new webpack.LoaderOptionsPlugin({debug: true}),
        new webpack.ProvidePlugin({jQuery: 'jquery', $: 'jquery', jquery: 'jquery'})
    ],
    module: {
        rules: [
            {
                test: require.resolve("typeit"),
                loaders: ['imports-loader?jQuery=jquery,this=>window'],
                exclude: /(node_modules|bower_components)/
            }, {
                test: /\.(js|jsx)$/,
                use: ['babel-loader'],
                exclude: /(node_modules|bower_components)/,
                // use: ['react-hot-loader','babel-loader']
            }
        ]
    }

};
```

This is how I am including. I also tried import.
```
require("typeit")
```

This combination doesn't work. I

**Comment by alexmacarthur** [comment]
I'm very unfamiliar with Webpack configuration, so not sure how much help I can be with this. 

Do you know for sure what order the scripts are being loaded after bundling? If TypeIt's being included before jQuery, it won't work. 

Is TypeIt being downloaded to your node_modules directory? Or is it in some other location?

**Comment by VarunBatraIT** [comment]
Hi Alex

typeit is in node_modules it is installed as npm package. jQuery/$ is defined and typeit is being loaded after jQuery. Everything, I am using is as a npm packages. **Error is $().typeIt is undefined**.

Thanks

**Comment by VarunBatraIT** [comment]
Just to be clear, I followed this:

https://webpack.js.org/loaders/imports-loader/

**Comment by alexmacarthur** [comment]
Not an issue with the plugin itself, so going to close this.
