### ISSUE TITLE
Angular - Cannot find type definition file for 'web-animations-js'.

### ISSUE THREAD

**Issue by BugProg** [alexmacarthur/typeit#340]
Hi !

I tried to install TypeIt on my angular project with npm: `npm install typeit`.
Then I imported TypeIt like this: `import TypeIt from 'typeit';`
But I got this error:
```
Error: node_modules/typeit/dist/types.d.ts:1:23 - error TS2688: Cannot find type definition file for 'web-animations-js'.
1 /// <reference types="web-animations-js" />
                        ~~~~~~~~~~~~~~~~~

Error: node_modules/typeit/dist/types.d.ts:8:14 - error TS2304: Cannot find name 'AnimationKeyFrame'.
8     frames?: AnimationKeyFrame[];
               ~~~~~~~~~~~~~~~~~

Error: node_modules/typeit/dist/types.d.ts:9:23 - error TS2552: Cannot find name 'AnimationEffectTiming'. Did you mean 'AnimationEffect'?
9     options?: Partial<AnimationEffectTiming>;
                        ~~~~~~~~~~~~~~~~~~~~~

node_modules/typescript/lib/lib.dom.d.ts:2177:13
    2177 declare var AnimationEffect: {
                     ~~~~~~~~~~~~~~~
    'AnimationEffect' is declared here.
```

### Package Versions:
* **typeit**: 8.7.1
* **Angular**: 15.1.2
* **typescript**: 4.9.4

**Comment by BugProg** [comment]
Hi !
I was able to fix the issue by installing `@types/web-animations-js`

Then I declare new TypeIt instance like this :
```TS
new (TypeIt as any)("#typeIt", {
 speed: 100,
 loop: true
}).go();
```

Happy to hear better ways to implement TypeIt in Angular :)

**Comment by alexmacarthur** [comment]
I just included these types as dependency for the future (rather than a dev dependency), so others shouldn't run into the same issue. Thanks for letting me know about this & sorry for the delay.

https://github.com/alexmacarthur/typeit/blob/master/packages/typeit/package.json#L48
