### ISSUE TITLE
Warning showing as console Error on latest Next/React.

### ISSUE THREAD

**Issue by joemcbroom** [alexmacarthur/typeit#346]
> Warning: TypeIt: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.

This 'warning' is registering as an error on Next 13 - not sure if that's caused by the library or the framework or just the latest React.  I tried to fork and fix the underlying issue but honestly I'm a bit out of my depth there.

Thought I'd share - thanks.

```
"next": "^13.2.4",
"react": "^18.2.0",
...
"typeit-react": "^2.6.4"
```

![Screenshot 2023-03-30 at 11 01 20 PM](https://user-images.githubusercontent.com/22060335/229012401-c4eb0ee0-4ce2-4773-93ef-5062bc740422.png)

**Comment by alexmacarthur** [comment]
Super delayed, but this has been fixed. Thanks for reporting!

https://github.com/alexmacarthur/typeit/releases/tag/typeit-react%402.7.0

**Comment by MaximilianWalker** [comment]
> Super delayed, but this has been fixed. Thanks for reporting!
> 
> https://github.com/alexmacarthur/typeit/releases/tag/typeit-react%402.7.0

I had this problem for so long and it was so annoying in Next. Thanks a lot!
