### ISSUE TITLE
Delete between strings with React

### ISSUE THREAD

**Issue by garand** [alexmacarthur/typeit#349]
Is there a way in the React lib to delete everything between typing each string? I tried hooking into the afterString method but wasn't successful.

**Comment by amirhhashemi** [comment]
I was looking for the same thing today. I ended up typing and deleting strings manually:
```tsx
<TypeIt
  getBeforeInit={(instance) =>
    instance
      .type("Sustainable Future")
      .pause(2000)
      .delete(18)
      .type("Reducing Costs")
      .pause(2000)
      .delete(14)
      .type("Optimizing Performance")
  }
  options={{
    speed: 90,
    loop: true,
    loopDelay: 2000,
  }}
/>
```

**Comment by alexmacarthur** [comment]
Yep, @amirhhashemi's approach is what i'd recommend here. The React component is a fairly light wrapper over the vanilla library. If you're doing anything remotely complicated (even just typing & deleting strings), it's best to reach for the `getBeforeInit` hook.
