### ISSUE TITLE
Doesn't type on mobile

### ISSUE THREAD

**Issue by Stef-00012** [alexmacarthur/typeit#360]
When i visit the site on desktop it works perfectly, but when i visit the same site on mobile it shows the cursor but doesn't type

https://github.com/alexmacarthur/typeit/assets/81536172/a88a50f7-4072-4240-8b14-9b890927094f

**Comment by alexmacarthur** [comment]
Hm. This look like it might be an issue with the IntersectionObserver powering the "waitUntilVisible" option. If you're still seeing the problem and haven't already, could you try commenting out that option in the TypeIt initializer?

**Comment by Stef-00012** [comment]
removing the `waitUntilVisible` fixes it
