### ISSUE TITLE
`Element` prop not working on typeit-react

### ISSUE THREAD

**Issue by cgranados16** [alexmacarthur/typeit#369]
From the docs, [**Choosing Your Own Element**](https://www.typeitjs.com/docs/react/#choosing-your-own-element):

> Out of the box, a span element is used to contain the typing animation. To choose your own element, use the element prop.
```javascript
import TypeIt from "typeit-react";

export default () => {
  return (
    <div className="App">
      <TypeIt element={"h3"}>This will be typed in an H3 tag.</TypeIt>
    </div>
  );
};
```
This is still being rendered as a `span` not the h3 defined in the code.
<img width="610" alt="Screenshot 2023-12-10 at 18 32 41" src="https://github.com/alexmacarthur/typeit/assets/18092598/d23c3762-1a9d-4a5d-943a-e1a74e8d763e">

**Comment by alexmacarthur** [comment]
sorry about that, @cgranados16! the documentation was incorrect. you should use the `as` prop for this. i've updated it. 

https://www.typeitjs.com/docs/react#choosing-your-own-element
