### ISSUE TITLE
Randomise Strings

### ISSUE THREAD

**Issue by wawanzs** [alexmacarthur/typeit#37]
I'm trying to make it to display the strings randomly. Would love to know if this is something possible to do 😄

**Comment by alexmacarthur** [comment]
Hi, @wawanzs. This isn't a feature I'll build in, but you can do this yourself if you want. Basically, you need to create an array of strings, and then randomize them before passing them in & initializing TypeIt. You'd probably use something like this to randomize the array items: 

https://stackoverflow.com/questions/5915096/get-random-item-from-javascript-array

**Comment by viktaur** [comment]
Hi, couldn't we have a `random: boolean` field we could pass to the options prop?
