### ISSUE TITLE
Does not worked unicode type

### ISSUE THREAD

**Issue by yurenlimbu** [alexmacarthur/typeit#38]
Is it possible to fix this?
Here are the screenshot
![1](https://cloud.githubusercontent.com/assets/5475657/25616684/ef7b2324-2f5d-11e7-86a0-985cac409aae.png)

**Comment by alexmacarthur** [comment]
Is this still an issue? Unicode characters appear to be working fine for me: 

https://codepen.io/alexmacarthur/pen/wPLmrX
