### ISSUE TITLE
Cannot read properties of null (reading 'useRef')

### ISSUE THREAD

**Issue by happylolonly** [alexmacarthur/typeit#383]
Hi, I have this issue, seems something with build step.

This not helped - https://github.com/cybercongress/cyb-ts/blob/d2f1dfd349ead1fe2e15d1ce9154fa05404635ae/webpack.config.common.js#L128

For not copied code to project, it is working.
https://github.com/cybercongress/cyb-ts/blob/d2f1dfd349ead1fe2e15d1ce9154fa05404635ae/src/features/adviser/Adviser/Adviser.tsx

<img width="1435" alt="image" src="https://github.com/alexmacarthur/typeit/assets/18665326/f75e1bfd-8cd6-4a0d-9260-95f713d5eb2f">

**Comment by bdgcypher** [comment]
I am also getting the same issue.

![image](https://github.com/user-attachments/assets/eaff0c6b-613a-447f-b392-230b0a9e62fd)

**Comment by alexmacarthur** [comment]
@bdgcypher Would you mind sharing which version of React you're using, as well as the bundler? (Vite, Webpack, etc.)

**Comment by alexmacarthur** [comment]
@happylolonly @bdgcypher Fixed! Would you be able to confirm this when you get a chance? You'll need version 2.7.7.

**Comment by bdgcypher** [comment]
Now after uninstalling and reinstalling I am getting this error, but only with typeit-react. 
![image](https://github.com/user-attachments/assets/e2593903-ac2a-495b-8069-49b7bafd15df)

**Comment by bdgcypher** [comment]
Also, my react version is 18.3.1 and my bundler is webpack

**Comment by alexmacarthur** [comment]
@bdgcypher Ah, try using the --legacy-peer-deps flag at the end of your 'npm install' command and it should work. I may remove those dependencies from peerDeps altogether for the future, but that'll get you going for now.

**Comment by bdgcypher** [comment]
That worked! Thanks a bunch man! This package rocks overall 👍
