### ISSUE TITLE
when type html  the cursor position got wrong position

### ISSUE THREAD

**Issue by k186** [alexmacarthur/typeit#387]
![image](https://github.com/user-attachments/assets/ee315b39-8629-4589-be2a-82ca97c95847)
![image](https://github.com/user-attachments/assets/4d43a2d9-84b0-47b8-a00f-5a1e276f186e)

hope to get a hook function for cursor in every type

**Comment by daydayup001001** [comment]
Can you tell me how it was resolved, please
🍵
