### ISSUE TITLE
move react and react-dom to peer dependencies

### ISSUE THREAD

**Issue by talentlessguy** [alexmacarthur/typeit#393]

**Comment by alexmacarthur** [comment]
Why's that?

**Comment by talentlessguy** [comment]
to prevent dependency duplication if i already have react installed

which is usually the case when using a 3rd party react library

**Comment by alexmacarthur** [comment]
@talentlessguy Done! Moved to `peerDependencies` in 2.7.7. Please let me know if you still see issues. Thanks for reporting this!
