### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by TheoBearman** [alexmacarthur/typeit#4]
Any way you could get typeit on a CDN? Just about to install it on of my sites now.

Great job and thanks in advance,

Theo

**Comment by alexmacarthur** [comment]
Great idea -- let me take care of this later today. Thanks for looking into using TypeIt!

**Comment by TheoBearman** [comment]
No problem. Now using it [here!](https://vatsim.theobearman.com)

**Comment by alexmacarthur** [comment]
@TheoBearman Waiting on a live CDN link. As soon as it's up, I'll post it here and in the readme. 

Nice site, by the way! Are you fine with me sharing that as an example of someone using TypeIt?

**Comment by TheoBearman** [comment]
Please do!

**Comment by alexmacarthur** [comment]
Great, thanks! 

Here's your CDN link. Let me know if you need help with anything else.  

Minified: https://cdn.jsdelivr.net/jquery.typeit/3.0.0/typeit.min.js
Unminified: https://cdn.jsdelivr.net/jquery.typeit/3.0.0/typeit.js

**Comment by TheoBearman** [comment]
I can confirm the CDN is working. Thanks a lot for listening to my feedback!
