### ISSUE TITLE
Feature: Keep chars from previous string

### ISSUE THREAD

**Issue by jsenecal** [alexmacarthur/typeit#41]
It would be nice to have a feature that would work in conjunction with `breakLines: false` where the script would only delete the last chars that are different from the previous string.

Example:
```
$('.type-it').typeIt({
    strings: ['I am a Jedi', 'I am Obi wan Kenobi'],
    breakLines: false,
    keepChars: true //suggested setting
});
```
Would first output "I am a Jedi" then delete only "a Jedi" then type "Obi wan Kenobi"

**Comment by alexmacarthur** [comment]
Hm... I'm open to this idea. Will consider in future release!

**Comment by sreuter** [comment]
It would be awesome if it could also leave the characters at the end of a string when only the starting characters change...

E.g. ["Onboard employees", "Offboard Employees", "Reward Employees"].

**Comment by jsenecal** [comment]
Hey @alexmacarthur when was this ever added ?
