### ISSUE TITLE
cannot type in different language

### ISSUE THREAD

**Issue by iashwinprasada** [alexmacarthur/typeit#44]
when i use a different language to type in, the special charecters are breaking up. however when the delete happens, the chars seem to be proper. 

here is an example for testing " ಇನ್‌ಪುಟ್ ಪರಿಕರಗಳನ್ನು ಆನ್‌ಲೈನ್‌ನಲ್ಲಿ ಪ್ರಯತ್ನಿಸಿ " 
to reproduce: paste this is the example window with "loop" - true

**Comment by alexmacarthur** [comment]
@iashwinprasada I'm not able to replicate this -- Are you noticing this as an issue with the latest release? 

Here's what I'm seeing: 
https://codepen.io/alexmacarthur/pen/wPLmrX
