### ISSUE TITLE
Cursor does not follow text if surrounded by HTML tags

### ISSUE THREAD

**Issue by sparkhead95** [alexmacarthur/typeit#47]
If you have different HTML tags and have TypeIt type them on separate lines, the cursor does not follow the text. Please see the example:
https://jsfiddle.net/Lss4yoqg/

**Comment by alexfromapex** [comment]
This is because you are surrounding your text with elements that are set to `display: block` by default, e.g. `<h1>` etc.  You just need to set your elements to `display: inline-block` to fix this:

https://jsfiddle.net/Lss4yoqg/7/

**Comment by sparkhead95** [comment]
@alexfromapex  Thankyou, that fixed it.
