### ISSUE TITLE
No way to change cursor character value

### ISSUE THREAD

**Issue by alexfromapex** [alexmacarthur/typeit#49]
Cursor character is currently a pipe character: `|`.  Would like the ability to customize it to be a Unicode half block character to simulate the cursor on a Bash terminal: ` ▌`

I think it would be super easy to make this a config option

http://www.fileformat.info/info/unicode/char/258c/index.htm

**Comment by alexmacarthur** [comment]
Great idea! Will keep this in mind for future release.

**Comment by lnpbk** [comment]
Added a quick PR for this as I wanted an underscore for the cursor character: https://github.com/alexmacarthur/typeit/pull/81

**Comment by alexmacarthur** [comment]
@alexfromapex Featured added with the help of @lnpbk. See latest release: 

https://github.com/alexmacarthur/typeit/releases/tag/v5.4.0
