### ISSUE TITLE
Callback function not triggered

### ISSUE THREAD

**Issue by thenlai** [alexmacarthur/typeit#5]
I am so sorry to throw a trouble, but that's what I got.

I was using the TypeIt in version 3.0.0, and I found that the callback function was never triggered. (The `loop` option already set as `false`.)

Tested browser:
  - Firefox 43.0.4
  - Chrome 48.0
  - Safari 9.0.3

on OS X Yosemite(Macbook Air).

With both the `*.min.js` and `*.js` tested.

I was wondering why. Thank you.

**Comment by alexmacarthur** [comment]
Thank you for letting me know! Issue has been fixed. Please use this release: https://github.com/alexmacarthur/typeit/releases/tag/v3.0.1

Thanks for using TypeIt!
