### ISSUE TITLE
Ability to pause/stop the current animation and resume/restart it

### ISSUE THREAD

**Issue by eamodio** [alexmacarthur/typeit#53]
It would be great if there was a way to stop (or better yet pause) the current animation.

I would like to pause/stop an animation when it is out of view and ideally resume/restart when it comes back into view. Currently, I can restart it by just resetting up TypeIt on the element again, but I don't have any way to stop the animation. And better than stop/restart would be a way to pause/resume, so that when it comes back in view it picks up where it left off.

**Comment by alexmacarthur** [comment]
Great feedback, @eamodio! I'm actually in the process of rebuilding TypeIt without a jQuery dependency, which will be finished soon. After that rolls out, I'll consider adding this functionality as well.

**Comment by alexmacarthur** [comment]
Feature added in the latest release. Just use `freeze()` and `unfreeze()`.

```js
var instance = new TypeIt('#element' { //--options });

instance.freeze(); //-- pause it.
instance.unfreeze(); //-- resume it.
```
