### ISSUE TITLE
Remove dist folder from git

### ISSUE THREAD

**Issue by thiamsantos** [alexmacarthur/typeit#61]
Remove dist folder from to git as it is a file automatically generated and we don't need to keep track of them. In that way would be possible to keep the pull requests more clean. To accomplish this just add the [dist folder](https://github.com/reactjs/redux/blob/master/.gitignore#L4) [to the `gitignore` file](https://github.com/developit/preact/blob/master/.gitignore#L4) and add a [files property](https://docs.npmjs.com/files/package.json#files) to the `package.json` specifying the files to be included in the package when download it from npm. Right now [all the repo is included](https://unpkg.com/typeit/).

I would be happy to send a pull request.

**Comment by alexmacarthur** [comment]
I like the idea of keeping my `dist` files out of the repository, but I'm opting to keep them in so that the production-ready files are ready to be grabbed by anyone who might just want to clone the repo without compiling them before use. 

Love the idea of adding a files property to my `package.json`, though. I went ahead & implemented that in 06536ba.

**Comment by thiamsantos** [comment]
> I like the idea of keeping my dist files out of the repository, but I'm opting to keep them in so that the production-ready files are ready to be grabbed by anyone who might just want to clone the repo without compiling them before use.

The people can grab the project on unpkg [here](https://unpkg.com/typeit/) and on jsdelivr [here](https://cdn.jsdelivr.net/npm/typeit/), there's no need to keep them on the repository. Just provide a link on readme and everyone will be happy.

**Comment by alexmacarthur** [comment]
Not a bad idea. I'll reopen and consider that.
