### ISSUE TITLE
Use rollup

### ISSUE THREAD

**Issue by thiamsantos** [alexmacarthur/typeit#63]
Use [rollup](https://rollupjs.org/) to decrease the size of the bundle.
 
The webpack team recommends it: https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c
> Use webpack for apps, and Rollup for libraries

I would be happy to send a pull request.

**Comment by alexmacarthur** [comment]
Please do! I've never used roll-up and be interested in seeing a setup.

**Comment by thiamsantos** [comment]
Cool, I will send a pull request soon!
