### ISSUE TITLE
Background clip isn't working with this.

### ISSUE THREAD

**Issue by Ranjan-Bagri** [alexmacarthur/typeit#67]
CSS property `background-clip:text` not working. How to fix this issue?

**Comment by alexmacarthur** [comment]
Hi, @Ranjan-Bagri. It looks like this is an issue not with TypeIt, but with the nature of setting the `background-clip` on elements with other HTML elements nested within them. 

In this example here, `background-clip` works fine with TypeIt, as long as I don't break lines or insert any nested HTML tags. 

However, with even static HTML, if I nest markup, the property doesn't behave as desired.
