### ISSUE TITLE
Option to Turn Cursor (and Blink) Off Once Typing Has Completed

### ISSUE THREAD

**Issue by TheoBearman** [alexmacarthur/typeit#7]
Can we build this in?

**Comment by alexmacarthur** [comment]
Thanks for the suggestion! I'll think about getting that in a future build and let you know when it's up. In the meantime, if you'd like to do that now, you can just use a callback. This should kill the cursor after the strings are finished typing: 

``` 
$('#typeItBox').typeIt({
     // options
   }, function(){
     // callback
     $('.c').remove();
   });
```

Also, you'll want to use the latest build (v3.0.1): https://cdn.jsdelivr.net/jquery.typeit/3.0.1/typeit.min.js The previous version had a callback bug -- fixed now. Thanks!

**Comment by alexfromapex** [comment]
Looks like in the latest version you need to use `$('.ti-cursor').remove();` in your callback.
