### ISSUE TITLE
Typing not working when `type` method called in closure

### ISSUE THREAD

**Issue by DivineOmega** [alexmacarthur/typeit#78]
I'm using code similar to the following, creating a new TypeIt instance, and then calling its `type` method inside a closure (when the form is submitted). 

Unfortunately, this doesn't seem to be working. I'm not certain why, as calling the `type` method outside of the closure works fine. Any help would be much appreciated.

I'm using jquery 3.2.1 and typeit 5.2.0.

```html
<p id="log"></p>

        <p>
            <form method="POST" action="#" id="conversationForm">
                <input type="text" id="userInput" autofocus />
                <input id="sendButton" type="submit" value="Send" />
            </form>
        </p>

        <script>

            var typeIt = new TypeIt('#log', { html: false });

            $('#conversationForm').submit(function() {

                typeIt.type('Test!');

                return false;
            });

</script>
```

**Comment by DivineOmega** [comment]
Thanks @alexmacarthur.

This works, but unfortunately means the content of `#log` is lost upon each submission. Ideally, I would like to extra text to be typed after what has already been typed.

**Comment by david-soyez** [comment]
same problem here, this is really annoying, impossible to write for than a word with it
