### ISSUE TITLE
Inaccurate delete() function when using repeated styles

### ISSUE THREAD

**Issue by zacklabadie** [alexmacarthur/typeit#83]
When building a queue of strings to be typed, the `delete()` function breaks after two back-to-back strings include HTML/styling. Instead of deleting the appropriate number of characters, it deletes a seemingly random, larger integer when the third styled string is parsed.

I've tested this using both `span` and `strong`, both of which break the expected function. Browser doesn't seem to make a difference. Everything works great removing all HTML and using plaintext strings instead. [Here's a codepen](https://codepen.io/zacklabadie/pen/rpQaRd).

Thanks for the great work!

**Comment by alexmacarthur** [comment]
Thanks for reporting! I'll check into what's going on.

**Comment by alexmacarthur** [comment]
@zacklabadie Fixed! This was caused by empty HTML tags sometimes being left behind during deletion. I've tested it with your CodePen and it appears to be working as expected.

https://github.com/alexmacarthur/typeit/releases/tag/v5.4.1

**Comment by zacklabadie** [comment]
@alexmacarthur Thanks a ton, you're quick! Very much appreciated!
