### ISSUE TITLE
Change to how `nextStringDelay` works

### ISSUE THREAD

**Issue by lnpbk** [alexmacarthur/typeit#85]
Currently if you specify a `nextStringDelay` property, after a string has completed, the delay value is halved, the text deleted, and then the rest of the delay before the next string starts. This is especially noticeable when having longer delays, where there are a couple of seconds of nothing happening.

In my use case I have (relevant options only):
```
{
    nextStringDelay: 5000,
    loopDelay: 5000
}
```
Where the cursor just blinks with no content for ~2 seconds.

I'm suggesting that we have the ability to set a time that the typed string is displayed for after it has completed, as it's arguably more important than the exact time between completion and the next string starting.

So my proposal is that you set a `completedDisplayTime` (or something like that). Upon completion of a string, it waits for this time in its entirety, then deletes and begins the next string.

**Comment by alexmacarthur** [comment]
@lnpbk Thanks for bring that up -- I see how the current implementation can be weird with longer delays. That said, I'm hesitant to introduce another option so similar to what's already included. What on your thoughts on this: 

As a "sub" option to `nextStringDelay`, you could set the delay for the end and beginning of a string by passing in an option instead. Then, you could still use the default half/half functionality, but also narrow it down for your use case. 

So, you could do this: 

```js
{
     nextStringDelay: {
          beginningOfString: 4000,
          endOfString: 4000
     }
}
```

Or you could do this:

```js
{
     nextStringDelay: 5000
}
```

At least with this, there wouldn't be another new option to juggle when setting up an instance.

**Comment by lnpbk** [comment]
@alexmacarthur I agree that perhaps another option confuses things.

The `nextStringDelay` option could accept an array, with the first item being before, and the 2nd after?

Using an array is less verbose, but obviously loses a little clarity. Possibly not an issue if the docs are clear?

```
{
     nextStringDelay: [4000, 4000]
}
```

**Comment by alexmacarthur** [comment]
@lnpbk I like that idea. Working on an implementation of that now. Thanks!

**Comment by lnpbk** [comment]
@alexmacarthur Awesome!

**Comment by alexmacarthur** [comment]
@lnpbk A new release is out with this functionality. Try it out and let me know if you have any more feedback.

**Comment by lnpbk** [comment]
@alexmacarthur Great addition. Nice work!
