### ISSUE TITLE
Feature: Change Cursor Color

### ISSUE THREAD

**Issue by thekinglaolu** [alexmacarthur/typeit#89]
Is it possible to have the cursor be a different colour from the written out text?

**Comment by alexmacarthur** [comment]
There's nothing built into TypeIt itself to manage that, but you can do it with CSS pretty easily. The cursor has a ".ti-cursor" attached to it. So, you can just declare something like: 

```css
.ti-cursor {
     color: blue !important;
}
```

Notice the `!important` flag. By default, the color is set to inherit the element you're typing inside, so you'll need this to override the color.
