### ISSUE TITLE
pause on string completion if using multiple strings

### ISSUE THREAD

**Issue by marcusvbp** [alexmacarthur/typeit#9]
Hi,

I want a method to pause the animation after the string completion, and a method to resume animation to next string.

Thanks e sorry the bad english.

**Comment by alexmacarthur** [comment]
@marcusvbp Just released a new version of TypeIt this afternoon. Introduces a set of companion functions that allows you to customize your typing like crazy, including inserting pauses wherever your like them. Perhaps it'll help accomplish what you're wanting to do.

Release: https://github.com/alexmacarthur/typeit/releases/tag/v4.0.0

Demos: https://macarthur.me/typeit/

**Comment by marcusvbp** [comment]
@alexmacarthur thanks, mate.
