### ISSUE TITLE
Support typing in inputs.

### ISSUE THREAD

**Issue by alexmacarthur** [alexmacarthur/typeit#98]

**Comment by mralexgray** [comment]
any update on this?

**Comment by alexmacarthur** [comment]
Hi, @mralexgray - unfortunately, haven't had a chance to work on this yet. I'm currently working on a revamped version of the entire library, so unsure of what the timeline would be for this feature.

**Comment by mralexgray** [comment]
i worked around this issue in my codebase by overlapping a sibling non-input element via markup and css.  maybe it will inspire a more integrated future built-in solution?

```pug
    label="text"
	input(type='text')
	.typed(id="something")
````

```stylus
    input[type='text']
        position absolute
   .typed
        float left
	position relative
	height 1.3em
````````

**Comment by alexmacarthur** [comment]
Done! TypeIt v6 now supports typing in text input and textarea elements.
