### ISSUE TITLE
Grab the instance element with callback

### ISSUE THREAD

**Issue by schmolzp** [alexmacarthur/typeit#99]
Thank you for this script! I am just trying to figure out how to grab the respective element of a specific instance. I tried using the afterComplete callback but it wasn't working the way I was expecting.

I was able to grab it when I used 
`afterString: function(step, queue, instance) { var el = instance.elements.item(0); }`

However, that only worked if I have one string, but I want to be able to use the pause and delete methods and then type an additional string. I get why it wouldn't work in this case. Is there a way to get this to work with afterComplete?

Thank you for any help you can provide!

**Comment by schmolzp** [comment]
I figured it out. In the documentation it says to only pass in the argument 'instance' but you also need to pass in the 'step' argument before it. That fixed the problem of not being able to access the specific instance.

I think you might want to update the documentation to make that clear.

Thanks again!

**Comment by alexmacarthur** [comment]
Thanks for reporting this! The documentation was correct, the code was wrong, I have removed the extra argument being passed to `afterComplete`, so now only the instance is passed.
